// Code generated by ogen, DO NOT EDIT.
package knoq

type AddEventsRes interface {
	addEventsRes()
}

type AddRoomsRes interface {
	addRoomsRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type DeleteEventRes interface {
	deleteEventRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteRoomRes interface {
	deleteRoomRes()
}

type GetGroupsRes interface {
	getGroupsRes()
}

type GetTagRes interface {
	getTagRes()
}

type GrantPrivilegeRes interface {
	grantPrivilegeRes()
}

type UnverifyRoomRes interface {
	unverifyRoomRes()
}

type UpdateEventRes interface {
	updateEventRes()
}

type UpdateGroupRes interface {
	updateGroupRes()
}

type VerifyRoomRes interface {
	verifyRoomRes()
}
