// Code generated by ogen, DO NOT EDIT.

package knoq

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddEventTagParams is parameters of addEventTag operation.
type AddEventTagParams struct {
	EventID uuid.UUID
}

func unpackAddEventTagParams(packed middleware.Parameters) (params AddEventTagParams) {
	{
		key := middleware.ParameterKey{
			Name: "eventID",
			In:   "path",
		}
		params.EventID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAddEventTagParams(args [1]string, argsEscaped bool, r *http.Request) (params AddEventTagParams, _ error) {
	// Decode path: eventID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "eventID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EventID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "eventID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AddMeToGroupParams is parameters of addMeToGroup operation.
type AddMeToGroupParams struct {
	GroupID uuid.UUID
}

func unpackAddMeToGroupParams(packed middleware.Parameters) (params AddMeToGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "groupID",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAddMeToGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params AddMeToGroupParams, _ error) {
	// Decode path: groupID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "groupID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteEventParams is parameters of deleteEvent operation.
type DeleteEventParams struct {
	EventID uuid.UUID
}

func unpackDeleteEventParams(packed middleware.Parameters) (params DeleteEventParams) {
	{
		key := middleware.ParameterKey{
			Name: "eventID",
			In:   "path",
		}
		params.EventID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteEventParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteEventParams, _ error) {
	// Decode path: eventID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "eventID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EventID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "eventID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteEventTagParams is parameters of deleteEventTag operation.
type DeleteEventTagParams struct {
	EventID uuid.UUID
	TagName string
}

func unpackDeleteEventTagParams(packed middleware.Parameters) (params DeleteEventTagParams) {
	{
		key := middleware.ParameterKey{
			Name: "eventID",
			In:   "path",
		}
		params.EventID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "tagName",
			In:   "path",
		}
		params.TagName = packed[key].(string)
	}
	return params
}

func decodeDeleteEventTagParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteEventTagParams, _ error) {
	// Decode path: eventID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "eventID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EventID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "eventID",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: tagName.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "tagName",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TagName = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "tagName",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteGroupParams is parameters of deleteGroup operation.
type DeleteGroupParams struct {
	GroupID uuid.UUID
}

func unpackDeleteGroupParams(packed middleware.Parameters) (params DeleteGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "groupID",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteGroupParams, _ error) {
	// Decode path: groupID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "groupID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteMeFromGroupParams is parameters of deleteMeFromGroup operation.
type DeleteMeFromGroupParams struct {
	GroupID uuid.UUID
}

func unpackDeleteMeFromGroupParams(packed middleware.Parameters) (params DeleteMeFromGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "groupID",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteMeFromGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteMeFromGroupParams, _ error) {
	// Decode path: groupID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "groupID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteRoomParams is parameters of deleteRoom operation.
type DeleteRoomParams struct {
	// 除外するイベントのID。.
	ExcludeEventID OptUUID
	RoomID         uuid.UUID
}

func unpackDeleteRoomParams(packed middleware.Parameters) (params DeleteRoomParams) {
	{
		key := middleware.ParameterKey{
			Name: "excludeEventID",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludeEventID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "roomID",
			In:   "path",
		}
		params.RoomID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteRoomParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteRoomParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: excludeEventID.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludeEventID",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludeEventIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotExcludeEventIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludeEventID.SetTo(paramsDotExcludeEventIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludeEventID",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: roomID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "roomID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.RoomID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roomID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCallbackParams is parameters of getCallback operation.
type GetCallbackParams struct {
	Session string
	// OAuth2.0のcode.
	Code string
}

func unpackGetCallbackParams(packed middleware.Parameters) (params GetCallbackParams) {
	{
		key := middleware.ParameterKey{
			Name: "session",
			In:   "cookie",
		}
		params.Session = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "code",
			In:   "query",
		}
		params.Code = packed[key].(string)
	}
	return params
}

func decodeGetCallbackParams(args [0]string, argsEscaped bool, r *http.Request) (params GetCallbackParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	c := uri.NewCookieDecoder(r)
	// Decode cookie: session.
	if err := func() error {
		cfg := uri.CookieParameterDecodingConfig{
			Name:    "session",
			Explode: true,
		}
		if err := c.HasParam(cfg); err == nil {
			if err := c.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Session = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "session",
			In:   "cookie",
			Err:  err,
		}
	}
	// Decode query: code.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "code",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Code = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "code",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetEventDetailParams is parameters of getEventDetail operation.
type GetEventDetailParams struct {
	EventID uuid.UUID
}

func unpackGetEventDetailParams(packed middleware.Parameters) (params GetEventDetailParams) {
	{
		key := middleware.ParameterKey{
			Name: "eventID",
			In:   "path",
		}
		params.EventID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetEventDetailParams(args [1]string, argsEscaped bool, r *http.Request) (params GetEventDetailParams, _ error) {
	// Decode path: eventID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "eventID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EventID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "eventID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetEventsParams is parameters of getEvents operation.
type GetEventsParams struct {
	// 特定の日時から。.
	DateBegin OptString
	// 特定の日時まで。.
	DateEnd OptString
	// Syntax: <br> top  : ε | expr, expr : term ( ( "||" | "&&" ) term)*<br> term : cmp | "(" expr
	// ")"<br> cmp  : Attr ( "==" | "!=" ) UUID<br> Attr : "event" | "user" | "group" | "tag".
	Q OptString
}

func unpackGetEventsParams(packed middleware.Parameters) (params GetEventsParams) {
	{
		key := middleware.ParameterKey{
			Name: "dateBegin",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.DateBegin = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "dateEnd",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.DateEnd = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Q = v.(OptString)
		}
	}
	return params
}

func decodeGetEventsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetEventsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: dateBegin.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "dateBegin",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDateBeginVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDateBeginVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DateBegin.SetTo(paramsDotDateBeginVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dateBegin",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: dateEnd.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "dateEnd",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDateEndVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDateEndVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DateEnd.SetTo(paramsDotDateEndVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dateEnd",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Q.SetTo(paramsDotQVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetEventsOfGroupParams is parameters of getEventsOfGroup operation.
type GetEventsOfGroupParams struct {
	GroupID uuid.UUID
}

func unpackGetEventsOfGroupParams(packed middleware.Parameters) (params GetEventsOfGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "groupID",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetEventsOfGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params GetEventsOfGroupParams, _ error) {
	// Decode path: groupID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "groupID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetEventsOfRoomParams is parameters of getEventsOfRoom operation.
type GetEventsOfRoomParams struct {
	RoomID uuid.UUID
}

func unpackGetEventsOfRoomParams(packed middleware.Parameters) (params GetEventsOfRoomParams) {
	{
		key := middleware.ParameterKey{
			Name: "roomID",
			In:   "path",
		}
		params.RoomID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetEventsOfRoomParams(args [1]string, argsEscaped bool, r *http.Request) (params GetEventsOfRoomParams, _ error) {
	// Decode path: roomID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "roomID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.RoomID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roomID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetGroupParams is parameters of getGroup operation.
type GetGroupParams struct {
	GroupID uuid.UUID
}

func unpackGetGroupParams(packed middleware.Parameters) (params GetGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "groupID",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params GetGroupParams, _ error) {
	// Decode path: groupID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "groupID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetIcalParams is parameters of getIcal operation.
type GetIcalParams struct {
	IcalToken IcalToken
	// Syntax: <br> top  : ε | expr, expr : term ( ( "||" | "&&" ) term)*<br> term : cmp | "(" expr
	// ")"<br> cmp  : Attr ( "==" | "!=" ) UUID<br> Attr : "event" | "user" | "group" | "tag".
	Q OptString
}

func unpackGetIcalParams(packed middleware.Parameters) (params GetIcalParams) {
	{
		key := middleware.ParameterKey{
			Name: "icalToken",
			In:   "path",
		}
		params.IcalToken = packed[key].(IcalToken)
	}
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Q = v.(OptString)
		}
	}
	return params
}

func decodeGetIcalParams(args [1]string, argsEscaped bool, r *http.Request) (params GetIcalParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: icalToken.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "icalToken",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotIcalTokenVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIcalTokenVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IcalToken = IcalToken(paramsDotIcalTokenVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "icalToken",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Q.SetTo(paramsDotQVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetMyEventsParams is parameters of getMyEvents operation.
type GetMyEventsParams struct {
	// どのような関係性でユーザーと結びつけるか。 取り得る値は、
	// admins(ユーザーが管理者), belongs(ユーザーが所属している),
	// belongs-or-admins(ユーザーが管理者または所属している)
	// イベントはさらに、attendees(not absent) 値がない場合は、belongs
	// として振る舞う.
	Relation OptUserRelation
}

func unpackGetMyEventsParams(packed middleware.Parameters) (params GetMyEventsParams) {
	{
		key := middleware.ParameterKey{
			Name: "relation",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Relation = v.(OptUserRelation)
		}
	}
	return params
}

func decodeGetMyEventsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetMyEventsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: relation.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "relation",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRelationVal UserRelation
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRelationVal = UserRelation(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Relation.SetTo(paramsDotRelationVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Relation.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "relation",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetMyGroupsParams is parameters of getMyGroups operation.
type GetMyGroupsParams struct {
	// どのような関係性でユーザーと結びつけるか。 取り得る値は、
	// admins(ユーザーが管理者), belongs(ユーザーが所属している),
	// belongs-or-admins(ユーザーが管理者または所属している)
	// イベントはさらに、attendees(not absent) 値がない場合は、belongs
	// として振る舞う.
	Relation OptUserRelation
}

func unpackGetMyGroupsParams(packed middleware.Parameters) (params GetMyGroupsParams) {
	{
		key := middleware.ParameterKey{
			Name: "relation",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Relation = v.(OptUserRelation)
		}
	}
	return params
}

func decodeGetMyGroupsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetMyGroupsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: relation.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "relation",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRelationVal UserRelation
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRelationVal = UserRelation(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Relation.SetTo(paramsDotRelationVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Relation.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "relation",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetRoomParams is parameters of getRoom operation.
type GetRoomParams struct {
	// 除外するイベントのID。.
	ExcludeEventID OptUUID
	RoomID         uuid.UUID
}

func unpackGetRoomParams(packed middleware.Parameters) (params GetRoomParams) {
	{
		key := middleware.ParameterKey{
			Name: "excludeEventID",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludeEventID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "roomID",
			In:   "path",
		}
		params.RoomID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetRoomParams(args [1]string, argsEscaped bool, r *http.Request) (params GetRoomParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: excludeEventID.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludeEventID",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludeEventIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotExcludeEventIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludeEventID.SetTo(paramsDotExcludeEventIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludeEventID",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: roomID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "roomID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.RoomID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roomID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetRoomsParams is parameters of getRooms operation.
type GetRoomsParams struct {
	// 特定の日時から。.
	DateBegin OptString
	// 特定の日時まで。.
	DateEnd OptString
	// 除外するイベントのID。.
	ExcludeEventID OptUUID
}

func unpackGetRoomsParams(packed middleware.Parameters) (params GetRoomsParams) {
	{
		key := middleware.ParameterKey{
			Name: "dateBegin",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.DateBegin = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "dateEnd",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.DateEnd = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "excludeEventID",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ExcludeEventID = v.(OptUUID)
		}
	}
	return params
}

func decodeGetRoomsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetRoomsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: dateBegin.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "dateBegin",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDateBeginVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDateBeginVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DateBegin.SetTo(paramsDotDateBeginVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dateBegin",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: dateEnd.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "dateEnd",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDateEndVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDateEndVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DateEnd.SetTo(paramsDotDateEndVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dateEnd",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: excludeEventID.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "excludeEventID",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotExcludeEventIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotExcludeEventIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ExcludeEventID.SetTo(paramsDotExcludeEventIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "excludeEventID",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserEventsParams is parameters of getUserEvents operation.
type GetUserEventsParams struct {
	// どのような関係性でユーザーと結びつけるか。 取り得る値は、
	// admins(ユーザーが管理者), belongs(ユーザーが所属している),
	// belongs-or-admins(ユーザーが管理者または所属している)
	// イベントはさらに、attendees(not absent) 値がない場合は、belongs
	// として振る舞う.
	Relation OptUserRelation
	UserID   uuid.UUID
}

func unpackGetUserEventsParams(packed middleware.Parameters) (params GetUserEventsParams) {
	{
		key := middleware.ParameterKey{
			Name: "relation",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Relation = v.(OptUserRelation)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "userID",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetUserEventsParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUserEventsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: relation.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "relation",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRelationVal UserRelation
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRelationVal = UserRelation(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Relation.SetTo(paramsDotRelationVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Relation.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "relation",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: userID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserGroupsParams is parameters of getUserGroups operation.
type GetUserGroupsParams struct {
	// どのような関係性でユーザーと結びつけるか。 取り得る値は、
	// admins(ユーザーが管理者), belongs(ユーザーが所属している),
	// belongs-or-admins(ユーザーが管理者または所属している)
	// イベントはさらに、attendees(not absent) 値がない場合は、belongs
	// として振る舞う.
	Relation OptUserRelation
	UserID   uuid.UUID
}

func unpackGetUserGroupsParams(packed middleware.Parameters) (params GetUserGroupsParams) {
	{
		key := middleware.ParameterKey{
			Name: "relation",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Relation = v.(OptUserRelation)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "userID",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetUserGroupsParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUserGroupsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: relation.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "relation",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRelationVal UserRelation
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRelationVal = UserRelation(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Relation.SetTo(paramsDotRelationVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Relation.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "relation",
			In:   "query",
			Err:  err,
		}
	}
	// Decode path: userID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUsersParams is parameters of getUsers operation.
type GetUsersParams struct {
	// アカウントがアクティブでないユーザーを含めるかどうか。 |
	// traQ由来のquery。 | de.
	IncludeSuspended OptBool
}

func unpackGetUsersParams(packed middleware.Parameters) (params GetUsersParams) {
	{
		key := middleware.ParameterKey{
			Name: "include-suspended",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeSuspended = v.(OptBool)
		}
	}
	return params
}

func decodeGetUsersParams(args [0]string, argsEscaped bool, r *http.Request) (params GetUsersParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: include-suspended.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include-suspended",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeSuspendedVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeSuspendedVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeSuspended.SetTo(paramsDotIncludeSuspendedVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include-suspended",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GrantPrivilegeParams is parameters of grantPrivilege operation.
type GrantPrivilegeParams struct {
	UserID uuid.UUID
}

func unpackGrantPrivilegeParams(packed middleware.Parameters) (params GrantPrivilegeParams) {
	{
		key := middleware.ParameterKey{
			Name: "userID",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGrantPrivilegeParams(args [1]string, argsEscaped bool, r *http.Request) (params GrantPrivilegeParams, _ error) {
	// Decode path: userID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UnverifyRoomParams is parameters of unverifyRoom operation.
type UnverifyRoomParams struct {
	RoomID uuid.UUID
}

func unpackUnverifyRoomParams(packed middleware.Parameters) (params UnverifyRoomParams) {
	{
		key := middleware.ParameterKey{
			Name: "roomID",
			In:   "path",
		}
		params.RoomID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUnverifyRoomParams(args [1]string, argsEscaped bool, r *http.Request) (params UnverifyRoomParams, _ error) {
	// Decode path: roomID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "roomID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.RoomID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roomID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateEventParams is parameters of updateEvent operation.
type UpdateEventParams struct {
	EventID uuid.UUID
}

func unpackUpdateEventParams(packed middleware.Parameters) (params UpdateEventParams) {
	{
		key := middleware.ParameterKey{
			Name: "eventID",
			In:   "path",
		}
		params.EventID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateEventParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateEventParams, _ error) {
	// Decode path: eventID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "eventID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EventID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "eventID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateGroupParams is parameters of updateGroup operation.
type UpdateGroupParams struct {
	GroupID uuid.UUID
}

func unpackUpdateGroupParams(packed middleware.Parameters) (params UpdateGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "groupID",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateGroupParams, _ error) {
	// Decode path: groupID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "groupID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "groupID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateScheduleParams is parameters of updateSchedule operation.
type UpdateScheduleParams struct {
	EventID uuid.UUID
}

func unpackUpdateScheduleParams(packed middleware.Parameters) (params UpdateScheduleParams) {
	{
		key := middleware.ParameterKey{
			Name: "eventID",
			In:   "path",
		}
		params.EventID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateScheduleParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateScheduleParams, _ error) {
	// Decode path: eventID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "eventID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.EventID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "eventID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// VerifyRoomParams is parameters of verifyRoom operation.
type VerifyRoomParams struct {
	RoomID uuid.UUID
}

func unpackVerifyRoomParams(packed middleware.Parameters) (params VerifyRoomParams) {
	{
		key := middleware.ParameterKey{
			Name: "roomID",
			In:   "path",
		}
		params.RoomID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeVerifyRoomParams(args [1]string, argsEscaped bool, r *http.Request) (params VerifyRoomParams, _ error) {
	// Decode path: roomID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "roomID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.RoomID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roomID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
