// Code generated by ogen, DO NOT EDIT.

package knoq

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddEventTag implements addEventTag operation.
//
// タグを追加.
//
// POST /events/{eventID}/tags
func (UnimplementedHandler) AddEventTag(ctx context.Context, req *RequestTag, params AddEventTagParams) error {
	return ht.ErrNotImplemented
}

// AddEvents implements addEvents operation.
//
// 部屋の使用宣言を行う.
//
// POST /events
func (UnimplementedHandler) AddEvents(ctx context.Context, req RequestEvent) (r AddEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddMeToGroup implements addMeToGroup operation.
//
// 自分をメンバーに追加する.
//
// PUT /groups/{groupID}/members/me
func (UnimplementedHandler) AddMeToGroup(ctx context.Context, params AddMeToGroupParams) error {
	return ht.ErrNotImplemented
}

// AddRooms implements addRooms operation.
//
// 部屋の情報追加.
//
// POST /rooms
func (UnimplementedHandler) AddRooms(ctx context.Context, req *RequestRoom) (r AddRoomsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGroup implements createGroup operation.
//
// グループを作成します。traQのグループとは無関係です。.
//
// POST /groups
func (UnimplementedHandler) CreateGroup(ctx context.Context, req *RequestGroup) (r CreateGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEvent implements deleteEvent operation.
//
// Adminsのみ.
//
// DELETE /events/{eventID}
func (UnimplementedHandler) DeleteEvent(ctx context.Context, params DeleteEventParams) (r DeleteEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEventTag implements deleteEventTag operation.
//
// Locked=falseだけ.
//
// DELETE /events/{eventID}/tags/{tagName}
func (UnimplementedHandler) DeleteEventTag(ctx context.Context, params DeleteEventTagParams) error {
	return ht.ErrNotImplemented
}

// DeleteGroup implements deleteGroup operation.
//
// グループの削除.
//
// DELETE /groups/{groupID}
func (UnimplementedHandler) DeleteGroup(ctx context.Context, params DeleteGroupParams) (r DeleteGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMeFromGroup implements deleteMeFromGroup operation.
//
// 自分しか削除出来ない。open=true.
//
// DELETE /groups/{groupID}/members/me
func (UnimplementedHandler) DeleteMeFromGroup(ctx context.Context, params DeleteMeFromGroupParams) error {
	return ht.ErrNotImplemented
}

// DeleteRoom implements deleteRoom operation.
//
// (関連する予約を削除する) エラーを出して削除を促す予定.
//
// DELETE /rooms/{roomID}
func (UnimplementedHandler) DeleteRoom(ctx context.Context, params DeleteRoomParams) (r DeleteRoomRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuthParams implements getAuthParams operation.
//
// リクエストに必要な情報を返す.
//
// POST /authParams
func (UnimplementedHandler) GetAuthParams(ctx context.Context) (r *AuthParams, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCallback implements getCallback operation.
//
// コールバックを検知して、トークンを取得します。.
//
// GET /callback
func (UnimplementedHandler) GetCallback(ctx context.Context, params GetCallbackParams) error {
	return ht.ErrNotImplemented
}

// GetEventActivities implements getEventActivities operation.
//
// 最近7日間に作成変更削除があったイベントを取得。
// 削除されたものを含んで返す。.
//
// Deprecated: schema marks this operation as deprecated.
//
// GET /activity/events
func (UnimplementedHandler) GetEventActivities(ctx context.Context) (r []ResponseEvent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEventDetail implements getEventDetail operation.
//
// 一件取得.
//
// GET /events/{eventID}
func (UnimplementedHandler) GetEventDetail(ctx context.Context, params GetEventDetailParams) (r *ResponseEventDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEvents implements getEvents operation.
//
// 使用宣言の情報を取得.
//
// GET /events
func (UnimplementedHandler) GetEvents(ctx context.Context, params GetEventsParams) (r []ResponseEvent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEventsOfGroup implements getEventsOfGroup operation.
//
// GroupIdのeventsを取得.
//
// GET /groups/{groupID}/events
func (UnimplementedHandler) GetEventsOfGroup(ctx context.Context, params GetEventsOfGroupParams) (r []ResponseEvent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEventsOfRoom implements getEventsOfRoom operation.
//
// 指定した部屋で行われるイベントを返す.
//
// GET /rooms/{roomID}/events
func (UnimplementedHandler) GetEventsOfRoom(ctx context.Context, params GetEventsOfRoomParams) (r []ResponseEvent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroup implements getGroup operation.
//
// 一件取得.
//
// GET /groups/{groupID}
func (UnimplementedHandler) GetGroup(ctx context.Context, params GetGroupParams) (r *ResponseGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroups implements getGroups operation.
//
// すべてのグループを取得する.
//
// GET /groups
func (UnimplementedHandler) GetGroups(ctx context.Context) (r GetGroupsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIcal implements getIcal operation.
//
// Icalを取得.
//
// GET /ical/v1/{icalToken}
func (UnimplementedHandler) GetIcal(ctx context.Context, params GetIcalParams) (r GetIcalOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIcalSecret implements getIcalSecret operation.
//
// /ical で使う`secret`を取得.
//
// GET /users/me/ical
func (UnimplementedHandler) GetIcalSecret(ctx context.Context) (r *IcalSecret, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// 自分のユーザー情報を取得.
//
// GET /users/me
func (UnimplementedHandler) GetMe(ctx context.Context) (r *ResponseUser, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyEvents implements getMyEvents operation.
//
// 所属しているイベントを返す.
//
// GET /users/me/events
func (UnimplementedHandler) GetMyEvents(ctx context.Context, params GetMyEventsParams) (r []ResponseEvent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyGroups implements getMyGroups operation.
//
// 自分の所属しているグループのIDを返す.
//
// GET /users/me/groups
func (UnimplementedHandler) GetMyGroups(ctx context.Context, params GetMyGroupsParams) (r UUIDs, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoom implements getRoom operation.
//
// 一件取得する.
//
// GET /rooms/{roomID}
func (UnimplementedHandler) GetRoom(ctx context.Context, params GetRoomParams) (r *ResponseRoom, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRooms implements getRooms operation.
//
// 進捗部屋の情報を取得.
//
// GET /rooms
func (UnimplementedHandler) GetRooms(ctx context.Context, params GetRoomsParams) (r []ResponseRoom, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTag implements getTag operation.
//
// タグを全て取得.
//
// GET /tags
func (UnimplementedHandler) GetTag(ctx context.Context) (r GetTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserEvents implements getUserEvents operation.
//
// 所属しているイベントを返す.
//
// GET /users/{userID}/events
func (UnimplementedHandler) GetUserEvents(ctx context.Context, params GetUserEventsParams) (r []ResponseEvent, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserGroups implements getUserGroups operation.
//
// ユーザーが所属しているグループのIDを返す.
//
// GET /users/{userID}/groups
func (UnimplementedHandler) GetUserGroups(ctx context.Context, params GetUserGroupsParams) (r UUIDs, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// ユーザー一覧を返す.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context, params GetUsersParams) (r []ResponseUser, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVersion implements getVersion operation.
//
// Version情報を取得.
//
// GET /version
func (UnimplementedHandler) GetVersion(ctx context.Context) (r *GetVersionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GrantPrivilege implements grantPrivilege operation.
//
// 管理者権限を付与したいuserのuserIDをパラメータに入れる.
// APIを叩く本人が管理者権限を持っている必要がある.
//
// PATCH /users/{userID}/privileged
func (UnimplementedHandler) GrantPrivilege(ctx context.Context, params GrantPrivilegeParams) (r GrantPrivilegeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostTag implements postTag operation.
//
// すでにある場合は、error.
//
// POST /tags
func (UnimplementedHandler) PostTag(ctx context.Context, req *RequestTag) (r *ResponseTag, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetIcalSecret implements resetIcalSecret operation.
//
// /ical で使う`secret`を再生成.
//
// PUT /users/me/ical
func (UnimplementedHandler) ResetIcalSecret(ctx context.Context) (r *IcalSecret, _ error) {
	return r, ht.ErrNotImplemented
}

// SyncUsers implements syncUsers operation.
//
// 管理者権限が必要。 traQのuserと同期します。
// 存在していないユーザーは作成されます。 stateが同期されます。.
//
// POST /users/sync
func (UnimplementedHandler) SyncUsers(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// UnverifyRoom implements unverifyRoom operation.
//
// 特権が必要。部屋が使用できることの確認を取り消す。.
//
// DELETE /rooms/{roomID}/verified
func (UnimplementedHandler) UnverifyRoom(ctx context.Context, params UnverifyRoomParams) (r UnverifyRoomRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEvent implements updateEvent operation.
//
// Adminsのみ.
//
// PUT /events/{eventID}
func (UnimplementedHandler) UpdateEvent(ctx context.Context, req RequestEvent, params UpdateEventParams) (r UpdateEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGroup implements updateGroup operation.
//
// Adminsのみ変更可能.
//
// PUT /groups/{groupID}
func (UnimplementedHandler) UpdateGroup(ctx context.Context, req *RequestGroup, params UpdateGroupParams) (r UpdateGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSchedule implements updateSchedule operation.
//
// 自分の参加予定を編集.
//
// PUT /events/{eventID}/attendees/me
func (UnimplementedHandler) UpdateSchedule(ctx context.Context, req *RequestSchedule, params UpdateScheduleParams) error {
	return ht.ErrNotImplemented
}

// VerifyRoom implements verifyRoom operation.
//
// 特権が必要。部屋が使用できることを確認する.
//
// POST /rooms/{roomID}/verified
func (UnimplementedHandler) VerifyRoom(ctx context.Context, params VerifyRoomParams) (r VerifyRoomRes, _ error) {
	return r, ht.ErrNotImplemented
}
