// Code generated by ogen, DO NOT EDIT.

package knoq

import (
	"io"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// AddEventsBadRequest is response for AddEvents operation.
type AddEventsBadRequest struct{}

func (*AddEventsBadRequest) addEventsRes() {}

// AddEventsForbidden is response for AddEvents operation.
type AddEventsForbidden struct{}

func (*AddEventsForbidden) addEventsRes() {}

// AddRoomsBadRequest is response for AddRooms operation.
type AddRoomsBadRequest struct{}

func (*AddRoomsBadRequest) addRoomsRes() {}

// AddRoomsForbidden is response for AddRooms operation.
type AddRoomsForbidden struct{}

func (*AddRoomsForbidden) addRoomsRes() {}

// Ref: #/components/schemas/authParams
type AuthParams struct {
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *AuthParams) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *AuthParams) SetURL(val string) {
	s.URL = val
}

// CreateGroupBadRequest is response for CreateGroup operation.
type CreateGroupBadRequest struct{}

func (*CreateGroupBadRequest) createGroupRes() {}

// DeleteEventForbidden is response for DeleteEvent operation.
type DeleteEventForbidden struct{}

func (*DeleteEventForbidden) deleteEventRes() {}

// DeleteEventNotFound is response for DeleteEvent operation.
type DeleteEventNotFound struct{}

func (*DeleteEventNotFound) deleteEventRes() {}

// DeleteGroupForbidden is response for DeleteGroup operation.
type DeleteGroupForbidden struct{}

func (*DeleteGroupForbidden) deleteGroupRes() {}

// DeleteGroupNotFound is response for DeleteGroup operation.
type DeleteGroupNotFound struct{}

func (*DeleteGroupNotFound) deleteGroupRes() {}

// DeleteRoomBadRequest is response for DeleteRoom operation.
type DeleteRoomBadRequest struct{}

func (*DeleteRoomBadRequest) deleteRoomRes() {}

// DeleteRoomForbidden is response for DeleteRoom operation.
type DeleteRoomForbidden struct{}

func (*DeleteRoomForbidden) deleteRoomRes() {}

// DeleteRoomOK is response for DeleteRoom operation.
type DeleteRoomOK struct{}

func (*DeleteRoomOK) deleteRoomRes() {}

// Ref: #/components/schemas/duration
type Duration struct {
	TimeStart string `json:"timeStart"`
	TimeEnd   string `json:"timeEnd"`
}

// GetTimeStart returns the value of TimeStart.
func (s *Duration) GetTimeStart() string {
	return s.TimeStart
}

// GetTimeEnd returns the value of TimeEnd.
func (s *Duration) GetTimeEnd() string {
	return s.TimeEnd
}

// SetTimeStart sets the value of TimeStart.
func (s *Duration) SetTimeStart(val string) {
	s.TimeStart = val
}

// SetTimeEnd sets the value of TimeEnd.
func (s *Duration) SetTimeEnd(val string) {
	s.TimeEnd = val
}

// GetCallbackFound is response for GetCallback operation.
type GetCallbackFound struct{}

// GetGroupsBadRequest is response for GetGroups operation.
type GetGroupsBadRequest struct{}

func (*GetGroupsBadRequest) getGroupsRes() {}

type GetGroupsOKApplicationJSON []ResponseGroup

func (*GetGroupsOKApplicationJSON) getGroupsRes() {}

type GetIcalOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetIcalOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// GetTagBadRequest is response for GetTag operation.
type GetTagBadRequest struct{}

func (*GetTagBadRequest) getTagRes() {}

type GetTagOKApplicationJSON []ResponseTag

func (*GetTagOKApplicationJSON) getTagRes() {}

type GetVersionOK struct {
	Version  OptString `json:"version"`
	Revision OptString `json:"revision"`
}

// GetVersion returns the value of Version.
func (s *GetVersionOK) GetVersion() OptString {
	return s.Version
}

// GetRevision returns the value of Revision.
func (s *GetVersionOK) GetRevision() OptString {
	return s.Revision
}

// SetVersion sets the value of Version.
func (s *GetVersionOK) SetVersion(val OptString) {
	s.Version = val
}

// SetRevision sets the value of Revision.
func (s *GetVersionOK) SetRevision(val OptString) {
	s.Revision = val
}

// GrantPrivilegeBadRequest is response for GrantPrivilege operation.
type GrantPrivilegeBadRequest struct{}

func (*GrantPrivilegeBadRequest) grantPrivilegeRes() {}

// GrantPrivilegeForbidden is response for GrantPrivilege operation.
type GrantPrivilegeForbidden struct{}

func (*GrantPrivilegeForbidden) grantPrivilegeRes() {}

// GrantPrivilegeNotFound is response for GrantPrivilege operation.
type GrantPrivilegeNotFound struct{}

func (*GrantPrivilegeNotFound) grantPrivilegeRes() {}

// Ref: #/components/schemas/icalSecret
type IcalSecret struct {
	Secret string `json:"secret"`
}

// GetSecret returns the value of Secret.
func (s *IcalSecret) GetSecret() string {
	return s.Secret
}

// SetSecret sets the value of Secret.
func (s *IcalSecret) SetSecret(val string) {
	s.Secret = val
}

type IcalToken string

// Ref: #/components/responses/Nocontent
type Nocontent struct{}

func (*Nocontent) deleteEventRes()    {}
func (*Nocontent) deleteGroupRes()    {}
func (*Nocontent) grantPrivilegeRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUserRelation returns new OptUserRelation with value set to v.
func NewOptUserRelation(v UserRelation) OptUserRelation {
	return OptUserRelation{
		Value: v,
		Set:   true,
	}
}

// OptUserRelation is optional UserRelation.
type OptUserRelation struct {
	Value UserRelation
	Set   bool
}

// IsSet returns true if OptUserRelation was set.
func (o OptUserRelation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUserRelation) Reset() {
	var v UserRelation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUserRelation) SetTo(v UserRelation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUserRelation) Get() (v UserRelation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUserRelation) Or(d UserRelation) UserRelation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/RequestEvent
// RequestEvent represents sum type.
type RequestEvent struct {
	Type                RequestEventType // switch on this field
	RequestEventInstant RequestEventInstant
	RequestEventStock   RequestEventStock
}

// RequestEventType is oneOf type of RequestEvent.
type RequestEventType string

// Possible values for RequestEventType.
const (
	RequestEventInstantRequestEvent RequestEventType = "RequestEventInstant"
	RequestEventStockRequestEvent   RequestEventType = "RequestEventStock"
)

// IsRequestEventInstant reports whether RequestEvent is RequestEventInstant.
func (s RequestEvent) IsRequestEventInstant() bool { return s.Type == RequestEventInstantRequestEvent }

// IsRequestEventStock reports whether RequestEvent is RequestEventStock.
func (s RequestEvent) IsRequestEventStock() bool { return s.Type == RequestEventStockRequestEvent }

// SetRequestEventInstant sets RequestEvent to RequestEventInstant.
func (s *RequestEvent) SetRequestEventInstant(v RequestEventInstant) {
	s.Type = RequestEventInstantRequestEvent
	s.RequestEventInstant = v
}

// GetRequestEventInstant returns RequestEventInstant and true boolean if RequestEvent is RequestEventInstant.
func (s RequestEvent) GetRequestEventInstant() (v RequestEventInstant, ok bool) {
	if !s.IsRequestEventInstant() {
		return v, false
	}
	return s.RequestEventInstant, true
}

// NewRequestEventInstantRequestEvent returns new RequestEvent from RequestEventInstant.
func NewRequestEventInstantRequestEvent(v RequestEventInstant) RequestEvent {
	var s RequestEvent
	s.SetRequestEventInstant(v)
	return s
}

// SetRequestEventStock sets RequestEvent to RequestEventStock.
func (s *RequestEvent) SetRequestEventStock(v RequestEventStock) {
	s.Type = RequestEventStockRequestEvent
	s.RequestEventStock = v
}

// GetRequestEventStock returns RequestEventStock and true boolean if RequestEvent is RequestEventStock.
func (s RequestEvent) GetRequestEventStock() (v RequestEventStock, ok bool) {
	if !s.IsRequestEventStock() {
		return v, false
	}
	return s.RequestEventStock, true
}

// NewRequestEventStockRequestEvent returns new RequestEvent from RequestEventStock.
func NewRequestEventStockRequestEvent(v RequestEventStock) RequestEvent {
	var s RequestEvent
	s.SetRequestEventStock(v)
	return s
}

// 部屋を作る.
// Ref: #/components/schemas/RequestEventInstant
type RequestEventInstant struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	// 部屋の共用をするか.
	SharedRoom bool      `json:"sharedRoom"`
	TimeStart  string    `json:"timeStart"`
	TimeEnd    string    `json:"timeEnd"`
	Place      string    `json:"place"`
	GroupId    uuid.UUID `json:"groupId"`
	// グループ外のユーザーが参加予定を出来るか.
	Open OptBool `json:"open"`
	// 編集権を持つユーザー.
	Admins []uuid.UUID                   `json:"admins"`
	Tags   []RequestEventInstantTagsItem `json:"tags"`
}

// GetName returns the value of Name.
func (s *RequestEventInstant) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *RequestEventInstant) GetDescription() string {
	return s.Description
}

// GetSharedRoom returns the value of SharedRoom.
func (s *RequestEventInstant) GetSharedRoom() bool {
	return s.SharedRoom
}

// GetTimeStart returns the value of TimeStart.
func (s *RequestEventInstant) GetTimeStart() string {
	return s.TimeStart
}

// GetTimeEnd returns the value of TimeEnd.
func (s *RequestEventInstant) GetTimeEnd() string {
	return s.TimeEnd
}

// GetPlace returns the value of Place.
func (s *RequestEventInstant) GetPlace() string {
	return s.Place
}

// GetGroupId returns the value of GroupId.
func (s *RequestEventInstant) GetGroupId() uuid.UUID {
	return s.GroupId
}

// GetOpen returns the value of Open.
func (s *RequestEventInstant) GetOpen() OptBool {
	return s.Open
}

// GetAdmins returns the value of Admins.
func (s *RequestEventInstant) GetAdmins() []uuid.UUID {
	return s.Admins
}

// GetTags returns the value of Tags.
func (s *RequestEventInstant) GetTags() []RequestEventInstantTagsItem {
	return s.Tags
}

// SetName sets the value of Name.
func (s *RequestEventInstant) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *RequestEventInstant) SetDescription(val string) {
	s.Description = val
}

// SetSharedRoom sets the value of SharedRoom.
func (s *RequestEventInstant) SetSharedRoom(val bool) {
	s.SharedRoom = val
}

// SetTimeStart sets the value of TimeStart.
func (s *RequestEventInstant) SetTimeStart(val string) {
	s.TimeStart = val
}

// SetTimeEnd sets the value of TimeEnd.
func (s *RequestEventInstant) SetTimeEnd(val string) {
	s.TimeEnd = val
}

// SetPlace sets the value of Place.
func (s *RequestEventInstant) SetPlace(val string) {
	s.Place = val
}

// SetGroupId sets the value of GroupId.
func (s *RequestEventInstant) SetGroupId(val uuid.UUID) {
	s.GroupId = val
}

// SetOpen sets the value of Open.
func (s *RequestEventInstant) SetOpen(val OptBool) {
	s.Open = val
}

// SetAdmins sets the value of Admins.
func (s *RequestEventInstant) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// SetTags sets the value of Tags.
func (s *RequestEventInstant) SetTags(val []RequestEventInstantTagsItem) {
	s.Tags = val
}

type RequestEventInstantTagsItem struct {
	Name   OptString `json:"name"`
	Locked OptBool   `json:"locked"`
}

// GetName returns the value of Name.
func (s *RequestEventInstantTagsItem) GetName() OptString {
	return s.Name
}

// GetLocked returns the value of Locked.
func (s *RequestEventInstantTagsItem) GetLocked() OptBool {
	return s.Locked
}

// SetName sets the value of Name.
func (s *RequestEventInstantTagsItem) SetName(val OptString) {
	s.Name = val
}

// SetLocked sets the value of Locked.
func (s *RequestEventInstantTagsItem) SetLocked(val OptBool) {
	s.Locked = val
}

// 既存の部屋を使う.
// Ref: #/components/schemas/RequestEventStock
type RequestEventStock struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	// 部屋の共用をするか.
	SharedRoom bool      `json:"sharedRoom"`
	TimeStart  string    `json:"timeStart"`
	TimeEnd    string    `json:"timeEnd"`
	RoomId     uuid.UUID `json:"roomId"`
	GroupId    uuid.UUID `json:"groupId"`
	// グループ外のユーザーが参加予定を出来るか.
	Open OptBool `json:"open"`
	// 編集権を持つユーザー.
	Admins []uuid.UUID                 `json:"admins"`
	Tags   []RequestEventStockTagsItem `json:"tags"`
}

// GetName returns the value of Name.
func (s *RequestEventStock) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *RequestEventStock) GetDescription() string {
	return s.Description
}

// GetSharedRoom returns the value of SharedRoom.
func (s *RequestEventStock) GetSharedRoom() bool {
	return s.SharedRoom
}

// GetTimeStart returns the value of TimeStart.
func (s *RequestEventStock) GetTimeStart() string {
	return s.TimeStart
}

// GetTimeEnd returns the value of TimeEnd.
func (s *RequestEventStock) GetTimeEnd() string {
	return s.TimeEnd
}

// GetRoomId returns the value of RoomId.
func (s *RequestEventStock) GetRoomId() uuid.UUID {
	return s.RoomId
}

// GetGroupId returns the value of GroupId.
func (s *RequestEventStock) GetGroupId() uuid.UUID {
	return s.GroupId
}

// GetOpen returns the value of Open.
func (s *RequestEventStock) GetOpen() OptBool {
	return s.Open
}

// GetAdmins returns the value of Admins.
func (s *RequestEventStock) GetAdmins() []uuid.UUID {
	return s.Admins
}

// GetTags returns the value of Tags.
func (s *RequestEventStock) GetTags() []RequestEventStockTagsItem {
	return s.Tags
}

// SetName sets the value of Name.
func (s *RequestEventStock) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *RequestEventStock) SetDescription(val string) {
	s.Description = val
}

// SetSharedRoom sets the value of SharedRoom.
func (s *RequestEventStock) SetSharedRoom(val bool) {
	s.SharedRoom = val
}

// SetTimeStart sets the value of TimeStart.
func (s *RequestEventStock) SetTimeStart(val string) {
	s.TimeStart = val
}

// SetTimeEnd sets the value of TimeEnd.
func (s *RequestEventStock) SetTimeEnd(val string) {
	s.TimeEnd = val
}

// SetRoomId sets the value of RoomId.
func (s *RequestEventStock) SetRoomId(val uuid.UUID) {
	s.RoomId = val
}

// SetGroupId sets the value of GroupId.
func (s *RequestEventStock) SetGroupId(val uuid.UUID) {
	s.GroupId = val
}

// SetOpen sets the value of Open.
func (s *RequestEventStock) SetOpen(val OptBool) {
	s.Open = val
}

// SetAdmins sets the value of Admins.
func (s *RequestEventStock) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// SetTags sets the value of Tags.
func (s *RequestEventStock) SetTags(val []RequestEventStockTagsItem) {
	s.Tags = val
}

type RequestEventStockTagsItem struct {
	Name   OptString `json:"name"`
	Locked OptBool   `json:"locked"`
}

// GetName returns the value of Name.
func (s *RequestEventStockTagsItem) GetName() OptString {
	return s.Name
}

// GetLocked returns the value of Locked.
func (s *RequestEventStockTagsItem) GetLocked() OptBool {
	return s.Locked
}

// SetName sets the value of Name.
func (s *RequestEventStockTagsItem) SetName(val OptString) {
	s.Name = val
}

// SetLocked sets the value of Locked.
func (s *RequestEventStockTagsItem) SetLocked(val OptBool) {
	s.Locked = val
}

// Ref: #/components/schemas/RequestGroup
type RequestGroup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Open        bool   `json:"open"`
	// グループのメンバー.
	Members []uuid.UUID `json:"members"`
	// 編集権を持つユーザー.
	Admins []uuid.UUID `json:"admins"`
}

// GetName returns the value of Name.
func (s *RequestGroup) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *RequestGroup) GetDescription() string {
	return s.Description
}

// GetOpen returns the value of Open.
func (s *RequestGroup) GetOpen() bool {
	return s.Open
}

// GetMembers returns the value of Members.
func (s *RequestGroup) GetMembers() []uuid.UUID {
	return s.Members
}

// GetAdmins returns the value of Admins.
func (s *RequestGroup) GetAdmins() []uuid.UUID {
	return s.Admins
}

// SetName sets the value of Name.
func (s *RequestGroup) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *RequestGroup) SetDescription(val string) {
	s.Description = val
}

// SetOpen sets the value of Open.
func (s *RequestGroup) SetOpen(val bool) {
	s.Open = val
}

// SetMembers sets the value of Members.
func (s *RequestGroup) SetMembers(val []uuid.UUID) {
	s.Members = val
}

// SetAdmins sets the value of Admins.
func (s *RequestGroup) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// Ref: #/components/schemas/RequestRoom
type RequestRoom struct {
	Place     string `json:"place"`
	TimeStart string `json:"timeStart"`
	TimeEnd   string `json:"timeEnd"`
	// 編集権を持つユーザー.
	Admins []uuid.UUID `json:"admins"`
}

// GetPlace returns the value of Place.
func (s *RequestRoom) GetPlace() string {
	return s.Place
}

// GetTimeStart returns the value of TimeStart.
func (s *RequestRoom) GetTimeStart() string {
	return s.TimeStart
}

// GetTimeEnd returns the value of TimeEnd.
func (s *RequestRoom) GetTimeEnd() string {
	return s.TimeEnd
}

// GetAdmins returns the value of Admins.
func (s *RequestRoom) GetAdmins() []uuid.UUID {
	return s.Admins
}

// SetPlace sets the value of Place.
func (s *RequestRoom) SetPlace(val string) {
	s.Place = val
}

// SetTimeStart sets the value of TimeStart.
func (s *RequestRoom) SetTimeStart(val string) {
	s.TimeStart = val
}

// SetTimeEnd sets the value of TimeEnd.
func (s *RequestRoom) SetTimeEnd(val string) {
	s.TimeEnd = val
}

// SetAdmins sets the value of Admins.
func (s *RequestRoom) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// Ref: #/components/schemas/RequestSchedule
type RequestSchedule struct {
	// Pending or absent or attendance.
	Schedule RequestScheduleSchedule `json:"schedule"`
}

// GetSchedule returns the value of Schedule.
func (s *RequestSchedule) GetSchedule() RequestScheduleSchedule {
	return s.Schedule
}

// SetSchedule sets the value of Schedule.
func (s *RequestSchedule) SetSchedule(val RequestScheduleSchedule) {
	s.Schedule = val
}

// Pending or absent or attendance.
type RequestScheduleSchedule string

const (
	RequestScheduleSchedulePending    RequestScheduleSchedule = "pending"
	RequestScheduleScheduleAbsent     RequestScheduleSchedule = "absent"
	RequestScheduleScheduleAttendance RequestScheduleSchedule = "attendance"
)

// AllValues returns all RequestScheduleSchedule values.
func (RequestScheduleSchedule) AllValues() []RequestScheduleSchedule {
	return []RequestScheduleSchedule{
		RequestScheduleSchedulePending,
		RequestScheduleScheduleAbsent,
		RequestScheduleScheduleAttendance,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RequestScheduleSchedule) MarshalText() ([]byte, error) {
	switch s {
	case RequestScheduleSchedulePending:
		return []byte(s), nil
	case RequestScheduleScheduleAbsent:
		return []byte(s), nil
	case RequestScheduleScheduleAttendance:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RequestScheduleSchedule) UnmarshalText(data []byte) error {
	switch RequestScheduleSchedule(data) {
	case RequestScheduleSchedulePending:
		*s = RequestScheduleSchedulePending
		return nil
	case RequestScheduleScheduleAbsent:
		*s = RequestScheduleScheduleAbsent
		return nil
	case RequestScheduleScheduleAttendance:
		*s = RequestScheduleScheduleAttendance
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RequestTag
type RequestTag struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *RequestTag) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *RequestTag) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/ResponseEvent
type ResponseEvent struct {
	EventId     uuid.UUID `json:"eventId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	// 部屋の共用をするか.
	SharedRoom bool      `json:"sharedRoom"`
	TimeStart  string    `json:"timeStart"`
	TimeEnd    string    `json:"timeEnd"`
	Place      string    `json:"place"`
	GroupName  string    `json:"groupName"`
	RoomId     uuid.UUID `json:"roomId"`
	GroupId    uuid.UUID `json:"groupId"`
	// グループ外のユーザーが参加予定を出来るか.
	Open bool `json:"open"`
	// 編集権を持つユーザー.
	Admins    []uuid.UUID                  `json:"admins"`
	Tags      []ResponseEventTagsItem      `json:"tags"`
	Attendees []ResponseEventAttendeesItem `json:"attendees"`
	CreatedBy uuid.UUID                    `json:"createdBy"`
	CreatedAt string                       `json:"createdAt"`
	UpdatedAt string                       `json:"updatedAt"`
}

// GetEventId returns the value of EventId.
func (s *ResponseEvent) GetEventId() uuid.UUID {
	return s.EventId
}

// GetName returns the value of Name.
func (s *ResponseEvent) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *ResponseEvent) GetDescription() string {
	return s.Description
}

// GetSharedRoom returns the value of SharedRoom.
func (s *ResponseEvent) GetSharedRoom() bool {
	return s.SharedRoom
}

// GetTimeStart returns the value of TimeStart.
func (s *ResponseEvent) GetTimeStart() string {
	return s.TimeStart
}

// GetTimeEnd returns the value of TimeEnd.
func (s *ResponseEvent) GetTimeEnd() string {
	return s.TimeEnd
}

// GetPlace returns the value of Place.
func (s *ResponseEvent) GetPlace() string {
	return s.Place
}

// GetGroupName returns the value of GroupName.
func (s *ResponseEvent) GetGroupName() string {
	return s.GroupName
}

// GetRoomId returns the value of RoomId.
func (s *ResponseEvent) GetRoomId() uuid.UUID {
	return s.RoomId
}

// GetGroupId returns the value of GroupId.
func (s *ResponseEvent) GetGroupId() uuid.UUID {
	return s.GroupId
}

// GetOpen returns the value of Open.
func (s *ResponseEvent) GetOpen() bool {
	return s.Open
}

// GetAdmins returns the value of Admins.
func (s *ResponseEvent) GetAdmins() []uuid.UUID {
	return s.Admins
}

// GetTags returns the value of Tags.
func (s *ResponseEvent) GetTags() []ResponseEventTagsItem {
	return s.Tags
}

// GetAttendees returns the value of Attendees.
func (s *ResponseEvent) GetAttendees() []ResponseEventAttendeesItem {
	return s.Attendees
}

// GetCreatedBy returns the value of CreatedBy.
func (s *ResponseEvent) GetCreatedBy() uuid.UUID {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ResponseEvent) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ResponseEvent) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetEventId sets the value of EventId.
func (s *ResponseEvent) SetEventId(val uuid.UUID) {
	s.EventId = val
}

// SetName sets the value of Name.
func (s *ResponseEvent) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *ResponseEvent) SetDescription(val string) {
	s.Description = val
}

// SetSharedRoom sets the value of SharedRoom.
func (s *ResponseEvent) SetSharedRoom(val bool) {
	s.SharedRoom = val
}

// SetTimeStart sets the value of TimeStart.
func (s *ResponseEvent) SetTimeStart(val string) {
	s.TimeStart = val
}

// SetTimeEnd sets the value of TimeEnd.
func (s *ResponseEvent) SetTimeEnd(val string) {
	s.TimeEnd = val
}

// SetPlace sets the value of Place.
func (s *ResponseEvent) SetPlace(val string) {
	s.Place = val
}

// SetGroupName sets the value of GroupName.
func (s *ResponseEvent) SetGroupName(val string) {
	s.GroupName = val
}

// SetRoomId sets the value of RoomId.
func (s *ResponseEvent) SetRoomId(val uuid.UUID) {
	s.RoomId = val
}

// SetGroupId sets the value of GroupId.
func (s *ResponseEvent) SetGroupId(val uuid.UUID) {
	s.GroupId = val
}

// SetOpen sets the value of Open.
func (s *ResponseEvent) SetOpen(val bool) {
	s.Open = val
}

// SetAdmins sets the value of Admins.
func (s *ResponseEvent) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// SetTags sets the value of Tags.
func (s *ResponseEvent) SetTags(val []ResponseEventTagsItem) {
	s.Tags = val
}

// SetAttendees sets the value of Attendees.
func (s *ResponseEvent) SetAttendees(val []ResponseEventAttendeesItem) {
	s.Attendees = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *ResponseEvent) SetCreatedBy(val uuid.UUID) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ResponseEvent) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ResponseEvent) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

// ユーザの参加状況.
type ResponseEventAttendeesItem struct {
	UserId uuid.UUID `json:"userId"`
	// Pending or absent or attendance.
	Schedule ResponseEventAttendeesItemSchedule `json:"schedule"`
}

// GetUserId returns the value of UserId.
func (s *ResponseEventAttendeesItem) GetUserId() uuid.UUID {
	return s.UserId
}

// GetSchedule returns the value of Schedule.
func (s *ResponseEventAttendeesItem) GetSchedule() ResponseEventAttendeesItemSchedule {
	return s.Schedule
}

// SetUserId sets the value of UserId.
func (s *ResponseEventAttendeesItem) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetSchedule sets the value of Schedule.
func (s *ResponseEventAttendeesItem) SetSchedule(val ResponseEventAttendeesItemSchedule) {
	s.Schedule = val
}

// Pending or absent or attendance.
type ResponseEventAttendeesItemSchedule string

const (
	ResponseEventAttendeesItemSchedulePending    ResponseEventAttendeesItemSchedule = "pending"
	ResponseEventAttendeesItemScheduleAbsent     ResponseEventAttendeesItemSchedule = "absent"
	ResponseEventAttendeesItemScheduleAttendance ResponseEventAttendeesItemSchedule = "attendance"
)

// AllValues returns all ResponseEventAttendeesItemSchedule values.
func (ResponseEventAttendeesItemSchedule) AllValues() []ResponseEventAttendeesItemSchedule {
	return []ResponseEventAttendeesItemSchedule{
		ResponseEventAttendeesItemSchedulePending,
		ResponseEventAttendeesItemScheduleAbsent,
		ResponseEventAttendeesItemScheduleAttendance,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResponseEventAttendeesItemSchedule) MarshalText() ([]byte, error) {
	switch s {
	case ResponseEventAttendeesItemSchedulePending:
		return []byte(s), nil
	case ResponseEventAttendeesItemScheduleAbsent:
		return []byte(s), nil
	case ResponseEventAttendeesItemScheduleAttendance:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResponseEventAttendeesItemSchedule) UnmarshalText(data []byte) error {
	switch ResponseEventAttendeesItemSchedule(data) {
	case ResponseEventAttendeesItemSchedulePending:
		*s = ResponseEventAttendeesItemSchedulePending
		return nil
	case ResponseEventAttendeesItemScheduleAbsent:
		*s = ResponseEventAttendeesItemScheduleAbsent
		return nil
	case ResponseEventAttendeesItemScheduleAttendance:
		*s = ResponseEventAttendeesItemScheduleAttendance
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ResponseEventDetail
type ResponseEventDetail struct {
	EventId     uuid.UUID `json:"eventId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	// 部屋の共用をするか.
	SharedRoom bool   `json:"sharedRoom"`
	TimeStart  string `json:"timeStart"`
	TimeEnd    string `json:"timeEnd"`
	Place      string `json:"place"`
	GroupName  string `json:"groupName"`
	// グループ外のユーザーが参加予定を出来るか.
	Open  bool          `json:"open"`
	Room  ResponseRoom  `json:"room"`
	Group ResponseGroup `json:"group"`
	// 編集権を持つユーザー.
	Admins    []uuid.UUID                        `json:"admins"`
	Tags      []ResponseEventDetailTagsItem      `json:"tags"`
	Attendees []ResponseEventDetailAttendeesItem `json:"attendees"`
	CreatedBy uuid.UUID                          `json:"createdBy"`
	CreatedAt string                             `json:"createdAt"`
	UpdatedAt string                             `json:"updatedAt"`
}

// GetEventId returns the value of EventId.
func (s *ResponseEventDetail) GetEventId() uuid.UUID {
	return s.EventId
}

// GetName returns the value of Name.
func (s *ResponseEventDetail) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *ResponseEventDetail) GetDescription() string {
	return s.Description
}

// GetSharedRoom returns the value of SharedRoom.
func (s *ResponseEventDetail) GetSharedRoom() bool {
	return s.SharedRoom
}

// GetTimeStart returns the value of TimeStart.
func (s *ResponseEventDetail) GetTimeStart() string {
	return s.TimeStart
}

// GetTimeEnd returns the value of TimeEnd.
func (s *ResponseEventDetail) GetTimeEnd() string {
	return s.TimeEnd
}

// GetPlace returns the value of Place.
func (s *ResponseEventDetail) GetPlace() string {
	return s.Place
}

// GetGroupName returns the value of GroupName.
func (s *ResponseEventDetail) GetGroupName() string {
	return s.GroupName
}

// GetOpen returns the value of Open.
func (s *ResponseEventDetail) GetOpen() bool {
	return s.Open
}

// GetRoom returns the value of Room.
func (s *ResponseEventDetail) GetRoom() ResponseRoom {
	return s.Room
}

// GetGroup returns the value of Group.
func (s *ResponseEventDetail) GetGroup() ResponseGroup {
	return s.Group
}

// GetAdmins returns the value of Admins.
func (s *ResponseEventDetail) GetAdmins() []uuid.UUID {
	return s.Admins
}

// GetTags returns the value of Tags.
func (s *ResponseEventDetail) GetTags() []ResponseEventDetailTagsItem {
	return s.Tags
}

// GetAttendees returns the value of Attendees.
func (s *ResponseEventDetail) GetAttendees() []ResponseEventDetailAttendeesItem {
	return s.Attendees
}

// GetCreatedBy returns the value of CreatedBy.
func (s *ResponseEventDetail) GetCreatedBy() uuid.UUID {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ResponseEventDetail) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ResponseEventDetail) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetEventId sets the value of EventId.
func (s *ResponseEventDetail) SetEventId(val uuid.UUID) {
	s.EventId = val
}

// SetName sets the value of Name.
func (s *ResponseEventDetail) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *ResponseEventDetail) SetDescription(val string) {
	s.Description = val
}

// SetSharedRoom sets the value of SharedRoom.
func (s *ResponseEventDetail) SetSharedRoom(val bool) {
	s.SharedRoom = val
}

// SetTimeStart sets the value of TimeStart.
func (s *ResponseEventDetail) SetTimeStart(val string) {
	s.TimeStart = val
}

// SetTimeEnd sets the value of TimeEnd.
func (s *ResponseEventDetail) SetTimeEnd(val string) {
	s.TimeEnd = val
}

// SetPlace sets the value of Place.
func (s *ResponseEventDetail) SetPlace(val string) {
	s.Place = val
}

// SetGroupName sets the value of GroupName.
func (s *ResponseEventDetail) SetGroupName(val string) {
	s.GroupName = val
}

// SetOpen sets the value of Open.
func (s *ResponseEventDetail) SetOpen(val bool) {
	s.Open = val
}

// SetRoom sets the value of Room.
func (s *ResponseEventDetail) SetRoom(val ResponseRoom) {
	s.Room = val
}

// SetGroup sets the value of Group.
func (s *ResponseEventDetail) SetGroup(val ResponseGroup) {
	s.Group = val
}

// SetAdmins sets the value of Admins.
func (s *ResponseEventDetail) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// SetTags sets the value of Tags.
func (s *ResponseEventDetail) SetTags(val []ResponseEventDetailTagsItem) {
	s.Tags = val
}

// SetAttendees sets the value of Attendees.
func (s *ResponseEventDetail) SetAttendees(val []ResponseEventDetailAttendeesItem) {
	s.Attendees = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *ResponseEventDetail) SetCreatedBy(val uuid.UUID) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ResponseEventDetail) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ResponseEventDetail) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

func (*ResponseEventDetail) addEventsRes()   {}
func (*ResponseEventDetail) updateEventRes() {}

// ユーザの参加状況.
type ResponseEventDetailAttendeesItem struct {
	UserId uuid.UUID `json:"userId"`
	// Pending or absent or attendance.
	Schedule ResponseEventDetailAttendeesItemSchedule `json:"schedule"`
}

// GetUserId returns the value of UserId.
func (s *ResponseEventDetailAttendeesItem) GetUserId() uuid.UUID {
	return s.UserId
}

// GetSchedule returns the value of Schedule.
func (s *ResponseEventDetailAttendeesItem) GetSchedule() ResponseEventDetailAttendeesItemSchedule {
	return s.Schedule
}

// SetUserId sets the value of UserId.
func (s *ResponseEventDetailAttendeesItem) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetSchedule sets the value of Schedule.
func (s *ResponseEventDetailAttendeesItem) SetSchedule(val ResponseEventDetailAttendeesItemSchedule) {
	s.Schedule = val
}

// Pending or absent or attendance.
type ResponseEventDetailAttendeesItemSchedule string

const (
	ResponseEventDetailAttendeesItemSchedulePending    ResponseEventDetailAttendeesItemSchedule = "pending"
	ResponseEventDetailAttendeesItemScheduleAbsent     ResponseEventDetailAttendeesItemSchedule = "absent"
	ResponseEventDetailAttendeesItemScheduleAttendance ResponseEventDetailAttendeesItemSchedule = "attendance"
)

// AllValues returns all ResponseEventDetailAttendeesItemSchedule values.
func (ResponseEventDetailAttendeesItemSchedule) AllValues() []ResponseEventDetailAttendeesItemSchedule {
	return []ResponseEventDetailAttendeesItemSchedule{
		ResponseEventDetailAttendeesItemSchedulePending,
		ResponseEventDetailAttendeesItemScheduleAbsent,
		ResponseEventDetailAttendeesItemScheduleAttendance,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResponseEventDetailAttendeesItemSchedule) MarshalText() ([]byte, error) {
	switch s {
	case ResponseEventDetailAttendeesItemSchedulePending:
		return []byte(s), nil
	case ResponseEventDetailAttendeesItemScheduleAbsent:
		return []byte(s), nil
	case ResponseEventDetailAttendeesItemScheduleAttendance:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResponseEventDetailAttendeesItemSchedule) UnmarshalText(data []byte) error {
	switch ResponseEventDetailAttendeesItemSchedule(data) {
	case ResponseEventDetailAttendeesItemSchedulePending:
		*s = ResponseEventDetailAttendeesItemSchedulePending
		return nil
	case ResponseEventDetailAttendeesItemScheduleAbsent:
		*s = ResponseEventDetailAttendeesItemScheduleAbsent
		return nil
	case ResponseEventDetailAttendeesItemScheduleAttendance:
		*s = ResponseEventDetailAttendeesItemScheduleAttendance
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// タグの配列.
type ResponseEventDetailTagsItem struct {
	TagId  uuid.UUID `json:"tagId"`
	Name   string    `json:"name"`
	Locked OptBool   `json:"locked"`
}

// GetTagId returns the value of TagId.
func (s *ResponseEventDetailTagsItem) GetTagId() uuid.UUID {
	return s.TagId
}

// GetName returns the value of Name.
func (s *ResponseEventDetailTagsItem) GetName() string {
	return s.Name
}

// GetLocked returns the value of Locked.
func (s *ResponseEventDetailTagsItem) GetLocked() OptBool {
	return s.Locked
}

// SetTagId sets the value of TagId.
func (s *ResponseEventDetailTagsItem) SetTagId(val uuid.UUID) {
	s.TagId = val
}

// SetName sets the value of Name.
func (s *ResponseEventDetailTagsItem) SetName(val string) {
	s.Name = val
}

// SetLocked sets the value of Locked.
func (s *ResponseEventDetailTagsItem) SetLocked(val OptBool) {
	s.Locked = val
}

// タグの配列.
type ResponseEventTagsItem struct {
	TagId  uuid.UUID `json:"tagId"`
	Name   string    `json:"name"`
	Locked OptBool   `json:"locked"`
}

// GetTagId returns the value of TagId.
func (s *ResponseEventTagsItem) GetTagId() uuid.UUID {
	return s.TagId
}

// GetName returns the value of Name.
func (s *ResponseEventTagsItem) GetName() string {
	return s.Name
}

// GetLocked returns the value of Locked.
func (s *ResponseEventTagsItem) GetLocked() OptBool {
	return s.Locked
}

// SetTagId sets the value of TagId.
func (s *ResponseEventTagsItem) SetTagId(val uuid.UUID) {
	s.TagId = val
}

// SetName sets the value of Name.
func (s *ResponseEventTagsItem) SetName(val string) {
	s.Name = val
}

// SetLocked sets the value of Locked.
func (s *ResponseEventTagsItem) SetLocked(val OptBool) {
	s.Locked = val
}

// Ref: #/components/schemas/ResponseGroup
type ResponseGroup struct {
	GroupId     uuid.UUID `json:"groupId"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Open        bool      `json:"open"`
	IsTraQGroup bool      `json:"isTraQGroup"`
	// グループのメンバー.
	Members []uuid.UUID `json:"members"`
	// 編集権を持つユーザー.
	Admins    []uuid.UUID `json:"admins"`
	CreatedBy uuid.UUID   `json:"createdBy"`
	CreatedAt string      `json:"createdAt"`
	UpdatedAt string      `json:"updatedAt"`
}

// GetGroupId returns the value of GroupId.
func (s *ResponseGroup) GetGroupId() uuid.UUID {
	return s.GroupId
}

// GetName returns the value of Name.
func (s *ResponseGroup) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *ResponseGroup) GetDescription() string {
	return s.Description
}

// GetOpen returns the value of Open.
func (s *ResponseGroup) GetOpen() bool {
	return s.Open
}

// GetIsTraQGroup returns the value of IsTraQGroup.
func (s *ResponseGroup) GetIsTraQGroup() bool {
	return s.IsTraQGroup
}

// GetMembers returns the value of Members.
func (s *ResponseGroup) GetMembers() []uuid.UUID {
	return s.Members
}

// GetAdmins returns the value of Admins.
func (s *ResponseGroup) GetAdmins() []uuid.UUID {
	return s.Admins
}

// GetCreatedBy returns the value of CreatedBy.
func (s *ResponseGroup) GetCreatedBy() uuid.UUID {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ResponseGroup) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ResponseGroup) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetGroupId sets the value of GroupId.
func (s *ResponseGroup) SetGroupId(val uuid.UUID) {
	s.GroupId = val
}

// SetName sets the value of Name.
func (s *ResponseGroup) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *ResponseGroup) SetDescription(val string) {
	s.Description = val
}

// SetOpen sets the value of Open.
func (s *ResponseGroup) SetOpen(val bool) {
	s.Open = val
}

// SetIsTraQGroup sets the value of IsTraQGroup.
func (s *ResponseGroup) SetIsTraQGroup(val bool) {
	s.IsTraQGroup = val
}

// SetMembers sets the value of Members.
func (s *ResponseGroup) SetMembers(val []uuid.UUID) {
	s.Members = val
}

// SetAdmins sets the value of Admins.
func (s *ResponseGroup) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *ResponseGroup) SetCreatedBy(val uuid.UUID) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ResponseGroup) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ResponseGroup) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

func (*ResponseGroup) createGroupRes() {}
func (*ResponseGroup) updateGroupRes() {}

// Ref: #/components/schemas/ResponseRoom
type ResponseRoom struct {
	RoomId    uuid.UUID `json:"roomId"`
	Place     string    `json:"place"`
	TimeStart string    `json:"timeStart"`
	TimeEnd   string    `json:"timeEnd"`
	// 部屋が使えることを保証する.
	Verified bool `json:"verified"`
	// どのイベントも使用していない時間帯.
	FreeTimes []Duration `json:"freeTimes"`
	// 部屋を共用すれば、使用できる時間帯.
	SharedTimes []Duration `json:"sharedTimes"`
	// 編集権を持つユーザー.
	Admins    []uuid.UUID `json:"admins"`
	CreatedBy uuid.UUID   `json:"createdBy"`
	CreatedAt string      `json:"createdAt"`
	UpdatedAt string      `json:"updatedAt"`
}

// GetRoomId returns the value of RoomId.
func (s *ResponseRoom) GetRoomId() uuid.UUID {
	return s.RoomId
}

// GetPlace returns the value of Place.
func (s *ResponseRoom) GetPlace() string {
	return s.Place
}

// GetTimeStart returns the value of TimeStart.
func (s *ResponseRoom) GetTimeStart() string {
	return s.TimeStart
}

// GetTimeEnd returns the value of TimeEnd.
func (s *ResponseRoom) GetTimeEnd() string {
	return s.TimeEnd
}

// GetVerified returns the value of Verified.
func (s *ResponseRoom) GetVerified() bool {
	return s.Verified
}

// GetFreeTimes returns the value of FreeTimes.
func (s *ResponseRoom) GetFreeTimes() []Duration {
	return s.FreeTimes
}

// GetSharedTimes returns the value of SharedTimes.
func (s *ResponseRoom) GetSharedTimes() []Duration {
	return s.SharedTimes
}

// GetAdmins returns the value of Admins.
func (s *ResponseRoom) GetAdmins() []uuid.UUID {
	return s.Admins
}

// GetCreatedBy returns the value of CreatedBy.
func (s *ResponseRoom) GetCreatedBy() uuid.UUID {
	return s.CreatedBy
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ResponseRoom) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ResponseRoom) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetRoomId sets the value of RoomId.
func (s *ResponseRoom) SetRoomId(val uuid.UUID) {
	s.RoomId = val
}

// SetPlace sets the value of Place.
func (s *ResponseRoom) SetPlace(val string) {
	s.Place = val
}

// SetTimeStart sets the value of TimeStart.
func (s *ResponseRoom) SetTimeStart(val string) {
	s.TimeStart = val
}

// SetTimeEnd sets the value of TimeEnd.
func (s *ResponseRoom) SetTimeEnd(val string) {
	s.TimeEnd = val
}

// SetVerified sets the value of Verified.
func (s *ResponseRoom) SetVerified(val bool) {
	s.Verified = val
}

// SetFreeTimes sets the value of FreeTimes.
func (s *ResponseRoom) SetFreeTimes(val []Duration) {
	s.FreeTimes = val
}

// SetSharedTimes sets the value of SharedTimes.
func (s *ResponseRoom) SetSharedTimes(val []Duration) {
	s.SharedTimes = val
}

// SetAdmins sets the value of Admins.
func (s *ResponseRoom) SetAdmins(val []uuid.UUID) {
	s.Admins = val
}

// SetCreatedBy sets the value of CreatedBy.
func (s *ResponseRoom) SetCreatedBy(val uuid.UUID) {
	s.CreatedBy = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ResponseRoom) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ResponseRoom) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

func (*ResponseRoom) addRoomsRes() {}

// Ref: #/components/schemas/ResponseTag
type ResponseTag struct {
	TagId     uuid.UUID `json:"tagId"`
	Name      string    `json:"name"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
}

// GetTagId returns the value of TagId.
func (s *ResponseTag) GetTagId() uuid.UUID {
	return s.TagId
}

// GetName returns the value of Name.
func (s *ResponseTag) GetName() string {
	return s.Name
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ResponseTag) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ResponseTag) GetUpdatedAt() string {
	return s.UpdatedAt
}

// SetTagId sets the value of TagId.
func (s *ResponseTag) SetTagId(val uuid.UUID) {
	s.TagId = val
}

// SetName sets the value of Name.
func (s *ResponseTag) SetName(val string) {
	s.Name = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ResponseTag) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ResponseTag) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/ResponseUser
type ResponseUser struct {
	UserId      uuid.UUID `json:"userId"`
	Name        string    `json:"name"`
	DisplayName string    `json:"displayName"`
	Icon        string    `json:"icon"`
	Privileged  bool      `json:"privileged"`
	// ユーザーアカウント状態 0: 停止 1: 有効 2: 一時停止.
	State int `json:"state"`
}

// GetUserId returns the value of UserId.
func (s *ResponseUser) GetUserId() uuid.UUID {
	return s.UserId
}

// GetName returns the value of Name.
func (s *ResponseUser) GetName() string {
	return s.Name
}

// GetDisplayName returns the value of DisplayName.
func (s *ResponseUser) GetDisplayName() string {
	return s.DisplayName
}

// GetIcon returns the value of Icon.
func (s *ResponseUser) GetIcon() string {
	return s.Icon
}

// GetPrivileged returns the value of Privileged.
func (s *ResponseUser) GetPrivileged() bool {
	return s.Privileged
}

// GetState returns the value of State.
func (s *ResponseUser) GetState() int {
	return s.State
}

// SetUserId sets the value of UserId.
func (s *ResponseUser) SetUserId(val uuid.UUID) {
	s.UserId = val
}

// SetName sets the value of Name.
func (s *ResponseUser) SetName(val string) {
	s.Name = val
}

// SetDisplayName sets the value of DisplayName.
func (s *ResponseUser) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetIcon sets the value of Icon.
func (s *ResponseUser) SetIcon(val string) {
	s.Icon = val
}

// SetPrivileged sets the value of Privileged.
func (s *ResponseUser) SetPrivileged(val bool) {
	s.Privileged = val
}

// SetState sets the value of State.
func (s *ResponseUser) SetState(val int) {
	s.State = val
}

// SyncUsersCreated is response for SyncUsers operation.
type SyncUsersCreated struct{}

type UUIDs []uuid.UUID

// UnverifyRoomBadRequest is response for UnverifyRoom operation.
type UnverifyRoomBadRequest struct{}

func (*UnverifyRoomBadRequest) unverifyRoomRes() {}

// UnverifyRoomForbidden is response for UnverifyRoom operation.
type UnverifyRoomForbidden struct{}

func (*UnverifyRoomForbidden) unverifyRoomRes() {}

// UnverifyRoomOK is response for UnverifyRoom operation.
type UnverifyRoomOK struct{}

func (*UnverifyRoomOK) unverifyRoomRes() {}

// UpdateEventBadRequest is response for UpdateEvent operation.
type UpdateEventBadRequest struct{}

func (*UpdateEventBadRequest) updateEventRes() {}

// UpdateEventForbidden is response for UpdateEvent operation.
type UpdateEventForbidden struct{}

func (*UpdateEventForbidden) updateEventRes() {}

// UpdateGroupBadRequest is response for UpdateGroup operation.
type UpdateGroupBadRequest struct{}

func (*UpdateGroupBadRequest) updateGroupRes() {}

// UpdateGroupForbidden is response for UpdateGroup operation.
type UpdateGroupForbidden struct{}

func (*UpdateGroupForbidden) updateGroupRes() {}

type UserRelation string

const (
	UserRelationAdmins          UserRelation = "admins"
	UserRelationBelongs         UserRelation = "belongs"
	UserRelationBelongsOrAdmins UserRelation = "belongs-or-admins"
	UserRelationAttendees       UserRelation = "attendees"
)

// AllValues returns all UserRelation values.
func (UserRelation) AllValues() []UserRelation {
	return []UserRelation{
		UserRelationAdmins,
		UserRelationBelongs,
		UserRelationBelongsOrAdmins,
		UserRelationAttendees,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UserRelation) MarshalText() ([]byte, error) {
	switch s {
	case UserRelationAdmins:
		return []byte(s), nil
	case UserRelationBelongs:
		return []byte(s), nil
	case UserRelationBelongsOrAdmins:
		return []byte(s), nil
	case UserRelationAttendees:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UserRelation) UnmarshalText(data []byte) error {
	switch UserRelation(data) {
	case UserRelationAdmins:
		*s = UserRelationAdmins
		return nil
	case UserRelationBelongs:
		*s = UserRelationBelongs
		return nil
	case UserRelationBelongsOrAdmins:
		*s = UserRelationBelongsOrAdmins
		return nil
	case UserRelationAttendees:
		*s = UserRelationAttendees
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// VerifyRoomBadRequest is response for VerifyRoom operation.
type VerifyRoomBadRequest struct{}

func (*VerifyRoomBadRequest) verifyRoomRes() {}

// VerifyRoomOK is response for VerifyRoom operation.
type VerifyRoomOK struct{}

func (*VerifyRoomOK) verifyRoomRes() {}
