services:
  web:
    build:
      context: .
      target: development
    volumes:
      - node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: .
          target: /home/node/app
        - action: sync+restart
          path: ./.env.local
          target: /home/node/app/.env.local
        - action: sync+restart
          path: ./.env.development.local
          target: /home/node/app/.env.development.local
        - action: sync+restart
          path: ./package-lock.json
          target: /home/node/app/package-lock.json
        - action: sync+restart
          path: ./src/modules/infra/prisma/schema.prisma
          target: /home/node/app/src/modules/infra/prisma/schema.prisma
    environment:
      DATABASE_URL: mysql://root:password@db:3306/dev
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: dev

volumes:
  node_modules:
  db_data:
