services:
  web:
    build:
      context: .
      target: development
    volumes:
      - .:/home/bun/app:cached
      - node_modules:/home/bun/app/node_modules
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: ./bun.lockb
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: dev
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: dev

volumes:
  node_modules:
  db_data:
