version: "3"

tasks:
  start:
    cmds:
      - docker compose watch --no-up & docker compose up --build
  attach:
    cmds:
      - docker compose exec -it web sh -c 'SKIP_ENV_VALIDATION=TRUE bash'
  mysql:
    cmds:
      - mysql -h 127.0.0.1 -P 3306 -u root -p dev
