// Code generated by ogen, DO NOT EDIT.

package traq

import (
	"context"

	"github.com/google/uuid"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActivateBot implements activateBot operation.
//
// 指定したBOTを有効化します。
// 対象のBOTの管理権限が必要です。.
//
// POST /bots/{botId}/actions/activate
func (UnimplementedHandler) ActivateBot(ctx context.Context, params ActivateBotParams) (r ActivateBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddMessageStamp implements addMessageStamp operation.
//
// 指定したメッセージに指定したスタンプを押します。.
//
// POST /messages/{messageId}/stamps/{stampId}
func (UnimplementedHandler) AddMessageStamp(ctx context.Context, req OptPostMessageStampRequest, params AddMessageStampParams) (r AddMessageStampRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddMyStar implements addMyStar operation.
//
// 指定したチャンネルをスターチャンネルに追加します。
// スター済みのチャンネルIDを指定した場合、204を返します。
// 不正なチャンネルIDを指定した場合、400を返します。.
//
// POST /users/me/stars
func (UnimplementedHandler) AddMyStar(ctx context.Context, req OptPostStarRequest) (r AddMyStarRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddMyUserTag implements addMyUserTag operation.
//
// 自分に新しくタグを追加します。.
//
// POST /users/me/tags
func (UnimplementedHandler) AddMyUserTag(ctx context.Context, req OptPostUserTagRequest) (r AddMyUserTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddUserGroupAdmin implements addUserGroupAdmin operation.
//
// 指定したグループに管理者を追加します。
// 対象のユーザーグループの管理者権限が必要です。.
//
// POST /groups/{groupId}/admins
func (UnimplementedHandler) AddUserGroupAdmin(ctx context.Context, req OptPostUserGroupAdminRequest, params AddUserGroupAdminParams) (r AddUserGroupAdminRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddUserGroupMember implements addUserGroupMember operation.
//
// 指定したグループにメンバーを追加します。
// 対象のユーザーグループの管理者権限が必要です。.
//
// POST /groups/{groupId}/members
func (UnimplementedHandler) AddUserGroupMember(ctx context.Context, req OptUserGroupMember, params AddUserGroupMemberParams) (r AddUserGroupMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddUserTag implements addUserTag operation.
//
// 指定したユーザーに指定したタグを追加します。
// Webhookユーザーにタグを追加することは出来ません。.
//
// POST /users/{userId}/tags
func (UnimplementedHandler) AddUserTag(ctx context.Context, req OptPostUserTagRequest, params AddUserTagParams) (r AddUserTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangeMyNotifyCitation implements changeMyNotifyCitation operation.
//
// メッセージ引用通知の設定情報を変更します.
//
// PUT /users/me/settings/notify-citation
func (UnimplementedHandler) ChangeMyNotifyCitation(ctx context.Context, req OptPutNotifyCitationRequest) (r ChangeMyNotifyCitationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangeMyPassword implements changeMyPassword operation.
//
// 自身のパスワードを変更します。.
//
// PUT /users/me/password
func (UnimplementedHandler) ChangeMyPassword(ctx context.Context, req OptPutMyPasswordRequest) (r ChangeMyPasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangeStampImage implements changeStampImage operation.
//
// 指定したスタンプの画像を変更します。.
//
// PUT /stamps/{stampId}/image
func (UnimplementedHandler) ChangeStampImage(ctx context.Context, req OptChangeStampImageReq, params ChangeStampImageParams) (r ChangeStampImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ChangeUserPassword implements changeUserPassword operation.
//
// 指定したユーザーのパスワードを変更します。
// 管理者権限が必要です。.
//
// PUT /users/{userId}/password
func (UnimplementedHandler) ChangeUserPassword(ctx context.Context, req OptPutUserPasswordRequest, params ChangeUserPasswordParams) (r ChangeUserPasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClipMessage implements clipMessage operation.
//
// 指定したメッセージを指定したクリップフォルダに追加します。.
//
// POST /clip-folders/{folderId}/messages
func (UnimplementedHandler) ClipMessage(ctx context.Context, req OptPostClipFolderMessageRequest, params ClipMessageParams) (r ClipMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConnectBotWS implements connectBotWS operation.
//
// # BOT WebSocketプロトコル
// ## 送信
// `コマンド:引数1:引数2:...`
// のような形式のTextMessageをサーバーに送信することで、このWebSocketセッションに対する設定が実行できます。
// ### `rtcstate`コマンド
// 自分のWebRTC状態を変更します。
// 他のコネクションが既に状態を保持している場合、変更することができません。
// `rtcstate:{チャンネルID}:({状態}:{セッションID})*`
// チャンネルIDにnullもしくは空文字を指定するか、状態にnullもしくは空文字を指定した場合、WebRTC状態はリセットされます。
// `rtcstate:null`, `rtcstate:`, `rtcstate:channelId:null`, `rtcstate:channelId:`
// コネクションが切断された場合、自分のWebRTC状態はリセットされます。
// ## 受信
// TextMessageとして各種イベントが`type`、`reqId`、`body`を持つJSONとして非同期に送られます。
// `body`の内容はHTTP Modeの場合のRequest Bodyと同様です。
// 例外として`ERROR`イベントは`reqId`を持ちません。
// 例: PINGイベント
// `{"type":"PING","reqId":"requestId","body":{"eventTime":"2019-05-07T04:50:48.582586882Z"}}`
// ### `ERROR`
// コマンドの引数が不正などの理由でコマンドが受理されなかった場合に送られます。
// 非同期に送られるため、必ずしもコマンドとの対応関係を確定できないことに注意してください。
// 本番環境ではERRORが送られないようにすることが望ましいです。
// `{"type":"ERROR","body":"message"}`.
//
// GET /bots/ws
func (UnimplementedHandler) ConnectBotWS(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// CreateBot implements createBot operation.
//
// BOTを作成します。
// 作成後に購読イベントの設定を行う必要があります。
// さらにHTTP Modeの場合はアクティベーションを行う必要があります。.
//
// POST /bots
func (UnimplementedHandler) CreateBot(ctx context.Context, req OptPostBotRequest) (r CreateBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateChannel implements createChannel operation.
//
// チャンネルを作成します。
// 階層が6以上になるチャンネルは作成できません。.
//
// POST /channels
func (UnimplementedHandler) CreateChannel(ctx context.Context, req OptPostChannelRequest) (r CreateChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateClient implements createClient operation.
//
// OAuth2クライアントを作成します。.
//
// POST /clients
func (UnimplementedHandler) CreateClient(ctx context.Context, req OptPostClientRequest) (r CreateClientRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateClipFolder implements createClipFolder operation.
//
// クリップフォルダを作成します。
// 既にあるフォルダと同名のフォルダを作成することは可能です。.
//
// POST /clip-folders
func (UnimplementedHandler) CreateClipFolder(ctx context.Context, req OptPostClipFolderRequest) (r CreateClipFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePin implements createPin operation.
//
// 指定したメッセージをピン留めします。
// アーカイブされているチャンネルのメッセージ・存在しないメッセージ・チャンネル当たりの上限数を超えたメッセージのピン留めはできません。.
//
// POST /messages/{messageId}/pin
func (UnimplementedHandler) CreatePin(ctx context.Context, params CreatePinParams) (r CreatePinRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateStampPalette implements createStampPalette operation.
//
// スタンプパレットを作成します。.
//
// POST /stamp-palettes
func (UnimplementedHandler) CreateStampPalette(ctx context.Context, req OptPostStampPaletteRequest) (r CreateStampPaletteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// ユーザーを登録します。
// 管理者権限が必要です。.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req OptPostUserRequest) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUserGroup implements createUserGroup operation.
//
// ユーザーグループを作成します。
// 作成者は自動的にグループ管理者になります。.
//
// POST /groups
func (UnimplementedHandler) CreateUserGroup(ctx context.Context, req OptPostUserGroupRequest) (r CreateUserGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWebhook implements createWebhook operation.
//
// Webhookを新規作成します。
// `secret`が空文字の場合、insecureウェブフックが作成されます。.
//
// POST /webhooks
func (UnimplementedHandler) CreateWebhook(ctx context.Context, req OptPostWebhookRequest) (r CreateWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteBot implements deleteBot operation.
//
// 指定したBOTを削除します。
// 対象のBOTの管理権限が必要です。.
//
// DELETE /bots/{botId}
func (UnimplementedHandler) DeleteBot(ctx context.Context, params DeleteBotParams) (r DeleteBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteClient implements deleteClient operation.
//
// 指定したOAuth2クライアントを削除します。
// 対象のクライアントの管理権限が必要です。正常に削除された場合、このクライアントに対する認可は全て取り消されます。.
//
// DELETE /clients/{clientId}
func (UnimplementedHandler) DeleteClient(ctx context.Context, params DeleteClientParams) (r DeleteClientRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteClipFolder implements deleteClipFolder operation.
//
// 指定したクリップフォルダを削除します。.
//
// DELETE /clip-folders/{folderId}
func (UnimplementedHandler) DeleteClipFolder(ctx context.Context, params DeleteClipFolderParams) (r DeleteClipFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFile implements deleteFile operation.
//
// 指定したファイルを削除します。
// 指定したファイルの削除権限が必要です。.
//
// DELETE /files/{fileId}
func (UnimplementedHandler) DeleteFile(ctx context.Context, params DeleteFileParams) (r DeleteFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMessage implements deleteMessage operation.
//
// 指定したメッセージを削除します。
// 自身が投稿したメッセージと自身が管理権限を持つWebhookとBOTが投稿したメッセージのみ削除することができます。
// アーカイブされているチャンネルのメッセージを編集することは出来ません。.
//
// DELETE /messages/{messageId}
func (UnimplementedHandler) DeleteMessage(ctx context.Context, params DeleteMessageParams) (r DeleteMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOgpCache implements deleteOgpCache operation.
//
// 指定されたURLのOGP情報のキャッシュを削除します。.
//
// DELETE /ogp/cache
func (UnimplementedHandler) DeleteOgpCache(ctx context.Context, params DeleteOgpCacheParams) (r DeleteOgpCacheRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteStamp implements deleteStamp operation.
//
// 指定したスタンプを削除します。
// 対象のスタンプの削除権限が必要です。.
//
// DELETE /stamps/{stampId}
func (UnimplementedHandler) DeleteStamp(ctx context.Context, params DeleteStampParams) (r DeleteStampRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteStampPalette implements deleteStampPalette operation.
//
// 指定したスタンプパレットを削除します。
// 対象のスタンプパレットの管理権限が必要です。.
//
// DELETE /stamp-palettes/{paletteId}
func (UnimplementedHandler) DeleteStampPalette(ctx context.Context, params DeleteStampPaletteParams) (r DeleteStampPaletteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUserGroup implements deleteUserGroup operation.
//
// 指定したユーザーグループを削除します。
// 対象のユーザーグループの管理者権限が必要です。.
//
// DELETE /groups/{groupId}
func (UnimplementedHandler) DeleteUserGroup(ctx context.Context, params DeleteUserGroupParams) (r DeleteUserGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWebhook implements deleteWebhook operation.
//
// 指定したWebhookを削除します。
// Webhookによって投稿されたメッセージは削除されません。.
//
// DELETE /webhooks/{webhookId}
func (UnimplementedHandler) DeleteWebhook(ctx context.Context, params DeleteWebhookParams) (r DeleteWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditBot implements editBot operation.
//
// 指定したBOTの情報を変更します。
// 対象のBOTの管理権限が必要です。
// BOT開発者UUIDを変更した場合は、変更先ユーザーにBOT管理権限が移譲され、自分自身は権限を失います。.
//
// PATCH /bots/{botId}
func (UnimplementedHandler) EditBot(ctx context.Context, req OptPatchBotRequest, params EditBotParams) (r EditBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditChannel implements editChannel operation.
//
// 指定したチャンネルの情報を変更します。
// 変更には権限が必要です。
// ルートチャンネルに移動させる場合は、`parent`に`00000000-0000-0000-0000-000000000000`を指定してください。.
//
// PATCH /channels/{channelId}
func (UnimplementedHandler) EditChannel(ctx context.Context, req OptPatchChannelRequest, params EditChannelParams) (r EditChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditChannelSubscribers implements editChannelSubscribers operation.
//
// 指定したチャンネルの通知購読者を編集します。
// リクエストに含めなかったユーザーの通知購読状態は変更しません。
// また、存在しないユーザーを指定した場合は無視されます。.
//
// PATCH /channels/{channelId}/subscribers
func (UnimplementedHandler) EditChannelSubscribers(ctx context.Context, req OptPatchChannelSubscribersRequest, params EditChannelSubscribersParams) (r EditChannelSubscribersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditChannelTopic implements editChannelTopic operation.
//
// 指定したチャンネルのトピックを編集します。
// アーカイブされているチャンネルのトピックは編集できません。.
//
// PUT /channels/{channelId}/topic
func (UnimplementedHandler) EditChannelTopic(ctx context.Context, req OptPutChannelTopicRequest, params EditChannelTopicParams) (r EditChannelTopicRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditClient implements editClient operation.
//
// 指定したOAuth2クライアントの情報を変更します。
// 対象のクライアントの管理権限が必要です。
// クライアント開発者UUIDを変更した場合は、変更先ユーザーにクライアント管理権限が移譲され、自分自身は権限を失います。.
//
// PATCH /clients/{clientId}
func (UnimplementedHandler) EditClient(ctx context.Context, req OptPatchClientRequest, params EditClientParams) (r EditClientRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditClipFolder implements editClipFolder operation.
//
// 指定したクリップフォルダの情報を編集します。.
//
// PATCH /clip-folders/{folderId}
func (UnimplementedHandler) EditClipFolder(ctx context.Context, req OptPatchClipFolderRequest, params EditClipFolderParams) (r EditClipFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditMe implements editMe operation.
//
// 自身のユーザー情報を変更します。.
//
// PATCH /users/me
func (UnimplementedHandler) EditMe(ctx context.Context, req OptPatchMeRequest) (r EditMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditMessage implements editMessage operation.
//
// 指定したメッセージを編集します。
// 自身が投稿したメッセージのみ編集することができます。
// アーカイブされているチャンネルのメッセージを編集することは出来ません。.
//
// PUT /messages/{messageId}
func (UnimplementedHandler) EditMessage(ctx context.Context, req OptPostMessageRequest, params EditMessageParams) (r EditMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditMyUserTag implements editMyUserTag operation.
//
// 自分の指定したタグの状態を変更します。.
//
// PATCH /users/me/tags/{tagId}
func (UnimplementedHandler) EditMyUserTag(ctx context.Context, req OptPatchUserTagRequest, params EditMyUserTagParams) (r EditMyUserTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditStamp implements editStamp operation.
//
// 指定したスタンプの情報を変更します。.
//
// PATCH /stamps/{stampId}
func (UnimplementedHandler) EditStamp(ctx context.Context, req OptPatchStampRequest, params EditStampParams) (r EditStampRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditStampPalette implements editStampPalette operation.
//
// 指定したスタンプパレットを編集します。
// リクエストのスタンプの配列の順番は保存されて変更されます。
// 対象のスタンプパレットの管理権限が必要です。.
//
// PATCH /stamp-palettes/{paletteId}
func (UnimplementedHandler) EditStampPalette(ctx context.Context, req OptPatchStampPaletteRequest, params EditStampPaletteParams) (r EditStampPaletteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditUser implements editUser operation.
//
// 指定したユーザーの情報を変更します。
// 管理者権限が必要です。.
//
// PATCH /users/{userId}
func (UnimplementedHandler) EditUser(ctx context.Context, req OptPatchUserRequest, params EditUserParams) (r EditUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditUserGroup implements editUserGroup operation.
//
// 指定したユーザーグループの情報を編集します。
// 対象のユーザーグループの管理者権限が必要です。.
//
// PATCH /groups/{groupId}
func (UnimplementedHandler) EditUserGroup(ctx context.Context, req OptPatchUserGroupRequest, params EditUserGroupParams) (r EditUserGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditUserGroupMember implements editUserGroupMember operation.
//
// 指定したユーザーグループ内の指定したユーザーの属性を編集します。
// 対象のユーザーグループの管理者権限が必要です。.
//
// PATCH /groups/{groupId}/members/{userId}
func (UnimplementedHandler) EditUserGroupMember(ctx context.Context, req OptPatchGroupMemberRequest, params EditUserGroupMemberParams) (r EditUserGroupMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditUserTag implements editUserTag operation.
//
// 指定したユーザーの指定したタグの状態を変更します。
// 他人の状態は変更できません。.
//
// PATCH /users/{userId}/tags/{tagId}
func (UnimplementedHandler) EditUserTag(ctx context.Context, req OptPatchUserTagRequest, params EditUserTagParams) (r EditUserTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EditWebhook implements editWebhook operation.
//
// 指定したWebhookの情報を変更します。.
//
// PATCH /webhooks/{webhookId}
func (UnimplementedHandler) EditWebhook(ctx context.Context, req OptPatchWebhookRequest, params EditWebhookParams) (r EditWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActivityTimeline implements getActivityTimeline operation.
//
// パブリックチャンネルの直近の投稿メッセージを作成日時の降順で取得します。
// `all`が`true`でない場合、購読チャンネルのみのタイムラインを取得します.
//
// GET /activity/timeline
func (UnimplementedHandler) GetActivityTimeline(ctx context.Context, params GetActivityTimelineParams) (r GetActivityTimelineRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBot implements getBot operation.
//
// 指定したBOTのBOT情報を取得します。
// BOT詳細情報を取得する場合は、対象のBOTの管理権限が必要です。.
//
// GET /bots/{botId}
func (UnimplementedHandler) GetBot(ctx context.Context, params GetBotParams) (r GetBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBotIcon implements getBotIcon operation.
//
// 指定したBOTのアイコン画像を取得を取得します。.
//
// GET /bots/{botId}/icon
func (UnimplementedHandler) GetBotIcon(ctx context.Context, params GetBotIconParams) (r GetBotIconRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBotLogs implements getBotLogs operation.
//
// 指定したBOTのイベントログを取得します。
// 対象のBOTの管理権限が必要です。.
//
// GET /bots/{botId}/logs
func (UnimplementedHandler) GetBotLogs(ctx context.Context, params GetBotLogsParams) (r GetBotLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBots implements getBots operation.
//
// BOT情報のリストを取得します。
// allを指定しない場合、自分が開発者のBOTのみを返します。.
//
// GET /bots
func (UnimplementedHandler) GetBots(ctx context.Context, params GetBotsParams) (r []Bot, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannel implements getChannel operation.
//
// 指定したチャンネルの情報を取得します。.
//
// GET /channels/{channelId}
func (UnimplementedHandler) GetChannel(ctx context.Context, params GetChannelParams) (r GetChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelBots implements getChannelBots operation.
//
// 指定したチャンネルに参加しているBOTのリストを取得します。.
//
// GET /channels/{channelId}/bots
func (UnimplementedHandler) GetChannelBots(ctx context.Context, params GetChannelBotsParams) (r GetChannelBotsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelPins implements getChannelPins operation.
//
// 指定したチャンネルにピン留めされているピンメッセージのリストを取得します。.
//
// GET /channels/{channelId}/pins
func (UnimplementedHandler) GetChannelPins(ctx context.Context, params GetChannelPinsParams) (r GetChannelPinsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelStats implements getChannelStats operation.
//
// 指定したチャンネルの統計情報を取得します。.
//
// GET /channels/{channelId}/stats
func (UnimplementedHandler) GetChannelStats(ctx context.Context, params GetChannelStatsParams) (r GetChannelStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelSubscribers implements getChannelSubscribers operation.
//
// 指定したチャンネルを通知購読しているユーザーのUUIDのリストを取得します。.
//
// GET /channels/{channelId}/subscribers
func (UnimplementedHandler) GetChannelSubscribers(ctx context.Context, params GetChannelSubscribersParams) (r GetChannelSubscribersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelTopic implements getChannelTopic operation.
//
// 指定したチャンネルのトピックを取得します。.
//
// GET /channels/{channelId}/topic
func (UnimplementedHandler) GetChannelTopic(ctx context.Context, params GetChannelTopicParams) (r GetChannelTopicRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannelViewers implements getChannelViewers operation.
//
// 指定したチャンネルの閲覧者のリストを取得します。.
//
// GET /channels/{channelId}/viewers
func (UnimplementedHandler) GetChannelViewers(ctx context.Context, params GetChannelViewersParams) (r GetChannelViewersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChannels implements getChannels operation.
//
// チャンネルのリストを取得します。.
//
// GET /channels
func (UnimplementedHandler) GetChannels(ctx context.Context, params GetChannelsParams) (r *ChannelList, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClient implements getClient operation.
//
// 指定したOAuth2クライアントの情報を取得します。
// 詳細情報の取得には対象のクライアントの管理権限が必要です。.
//
// GET /clients/{clientId}
func (UnimplementedHandler) GetClient(ctx context.Context, params GetClientParams) (r GetClientRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClients implements getClients operation.
//
// 自身が開発者のOAuth2クライアントのリストを取得します。
// `all`が`true`の場合、全開発者の全クライアントのリストを返します。.
//
// GET /clients
func (UnimplementedHandler) GetClients(ctx context.Context, params GetClientsParams) (r []OAuth2Client, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClipFolder implements getClipFolder operation.
//
// 指定したクリップフォルダの情報を取得します。.
//
// GET /clip-folders/{folderId}
func (UnimplementedHandler) GetClipFolder(ctx context.Context, params GetClipFolderParams) (r GetClipFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClipFolders implements getClipFolders operation.
//
// 自身が所有するクリップフォルダのリストを取得します。.
//
// GET /clip-folders
func (UnimplementedHandler) GetClipFolders(ctx context.Context) (r []ClipFolder, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClips implements getClips operation.
//
// 指定したフォルダ内のクリップのリストを取得します。
// `order`を指定しない場合、クリップした日時の新しい順で返されます。.
//
// GET /clip-folders/{folderId}/messages
func (UnimplementedHandler) GetClips(ctx context.Context, params GetClipsParams) (r GetClipsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDirectMessages implements getDirectMessages operation.
//
// 指定したユーザーとのダイレクトメッセージのリストを取得します。.
//
// GET /users/{userId}/messages
func (UnimplementedHandler) GetDirectMessages(ctx context.Context, params GetDirectMessagesParams) (r GetDirectMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFile implements getFile operation.
//
// 指定したファイル本体を取得します。
// 指定したファイルへのアクセス権限が必要です。.
//
// GET /files/{fileId}
func (UnimplementedHandler) GetFile(ctx context.Context, params GetFileParams) (r GetFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFileMeta implements getFileMeta operation.
//
// 指定したファイルのメタ情報を取得します。
// 指定したファイルへのアクセス権限が必要です。.
//
// GET /files/{fileId}/meta
func (UnimplementedHandler) GetFileMeta(ctx context.Context, params GetFileMetaParams) (r GetFileMetaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFiles implements getFiles operation.
//
// 指定したクエリでファイルメタのリストを取得します。
// クエリパラメータ`channelId`, `mine`の少なくともいずれかが必須です。.
//
// GET /files
func (UnimplementedHandler) GetFiles(ctx context.Context, params GetFilesParams) (r GetFilesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// 自身のユーザー詳細情報を取得します。.
//
// GET /users/me
func (UnimplementedHandler) GetMe(ctx context.Context) (r *MyUserDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMessage implements getMessage operation.
//
// 指定したメッセージを取得します。.
//
// GET /messages/{messageId}
func (UnimplementedHandler) GetMessage(ctx context.Context, params GetMessageParams) (r GetMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMessageClips implements getMessageClips operation.
//
// 対象のメッセージの自分のクリップの一覧を返します。.
//
// GET /messages/{messageId}/clips
func (UnimplementedHandler) GetMessageClips(ctx context.Context, params GetMessageClipsParams) (r GetMessageClipsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMessageStamps implements getMessageStamps operation.
//
// 指定したメッセージに押されているスタンプのリストを取得します。.
//
// GET /messages/{messageId}/stamps
func (UnimplementedHandler) GetMessageStamps(ctx context.Context, params GetMessageStampsParams) (r GetMessageStampsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMessages implements getMessages operation.
//
// 指定したチャンネルのメッセージのリストを取得します。.
//
// GET /channels/{channelId}/messages
func (UnimplementedHandler) GetMessages(ctx context.Context, params GetMessagesParams) (r GetMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyChannelSubscriptions implements getMyChannelSubscriptions operation.
//
// 自身のチャンネル購読状態を取得します。.
//
// GET /users/me/subscriptions
func (UnimplementedHandler) GetMyChannelSubscriptions(ctx context.Context) (r []UserSubscribeState, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyExternalAccounts implements getMyExternalAccounts operation.
//
// 自分に紐付けられている外部ログインアカウント一覧を取得します。.
//
// GET /users/me/ex-accounts
func (UnimplementedHandler) GetMyExternalAccounts(ctx context.Context) (r []ExternalProviderUser, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyIcon implements getMyIcon operation.
//
// 自分のアイコン画像を取得します。.
//
// GET /users/me/icon
func (UnimplementedHandler) GetMyIcon(ctx context.Context) (r GetMyIconRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyNotifyCitation implements getMyNotifyCitation operation.
//
// メッセージ引用通知の設定情報を変更します。.
//
// GET /users/me/settings/notify-citation
func (UnimplementedHandler) GetMyNotifyCitation(ctx context.Context) (r *GetNotifyCitation, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyQRCode implements getMyQRCode operation.
//
// 自身のQRコードを取得します。
// 返されたQRコードまたはトークンは、発行後の5分間のみ有効です.
//
// GET /users/me/qr-code
func (UnimplementedHandler) GetMyQRCode(ctx context.Context, params GetMyQRCodeParams) (r GetMyQRCodeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMySessions implements getMySessions operation.
//
// 自分のログインセッションのリストを取得します。.
//
// GET /users/me/sessions
func (UnimplementedHandler) GetMySessions(ctx context.Context) (r []LoginSession, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyStampHistory implements getMyStampHistory operation.
//
// 自分のスタンプ履歴を最大100件まで取得します。
// 結果は降順で返されます。
// このAPIが返すスタンプ履歴は厳密な履歴ではありません。.
//
// GET /users/me/stamp-history
func (UnimplementedHandler) GetMyStampHistory(ctx context.Context, params GetMyStampHistoryParams) (r []StampHistoryEntry, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyStars implements getMyStars operation.
//
// 自分がスターしているチャンネルのUUIDの配列を取得します。.
//
// GET /users/me/stars
func (UnimplementedHandler) GetMyStars(ctx context.Context) (r []uuid.UUID, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyTokens implements getMyTokens operation.
//
// 有効な自分に発行されたOAuth2トークンのリストを取得します。.
//
// GET /users/me/tokens
func (UnimplementedHandler) GetMyTokens(ctx context.Context) (r []ActiveOAuth2Token, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyUnreadChannels implements getMyUnreadChannels operation.
//
// 自分が現在未読のチャンネルの未読情報を取得します。.
//
// GET /users/me/unread
func (UnimplementedHandler) GetMyUnreadChannels(ctx context.Context) (r []UnreadChannel, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyUserTags implements getMyUserTags operation.
//
// 自分に付けられているタグの配列を取得します。.
//
// GET /users/me/tags
func (UnimplementedHandler) GetMyUserTags(ctx context.Context) (r []UserTag, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyViewStates implements getMyViewStates operation.
//
// 自身のチャンネル閲覧状態一覧を取得します。.
//
// GET /users/me/view-states
func (UnimplementedHandler) GetMyViewStates(ctx context.Context) (r []MyChannelViewState, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOAuth2Authorize implements getOAuth2Authorize operation.
//
// OAuth2 認可エンドポイント.
//
// GET /oauth2/authorize
func (UnimplementedHandler) GetOAuth2Authorize(ctx context.Context, params GetOAuth2AuthorizeParams) (r GetOAuth2AuthorizeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOIDCUserInfo implements getOIDCUserInfo operation.
//
// OIDCトークンを用いてユーザー詳細を取得します。
// OIDC UserInfo Endpointです。.
//
// GET /users/me/oidc
func (UnimplementedHandler) GetOIDCUserInfo(ctx context.Context) (r *OIDCUserInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOgp implements getOgp operation.
//
// 指定されたURLのOGP情報を取得します。
// 指定されたURLに対するOGP情報が見つからなかった場合、typeがemptyに設定された空のOGP情報を返します。.
//
// GET /ogp
func (UnimplementedHandler) GetOgp(ctx context.Context, params GetOgpParams) (r GetOgpRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOnlineUsers implements getOnlineUsers operation.
//
// 現在オンラインな(SSEまたはWSが接続中)ユーザーのUUIDのリストを返します。.
//
// GET /activity/onlines
func (UnimplementedHandler) GetOnlineUsers(ctx context.Context) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPin implements getPin operation.
//
// 指定したメッセージのピン留め情報を取得します。.
//
// GET /messages/{messageId}/pin
func (UnimplementedHandler) GetPin(ctx context.Context, params GetPinParams) (r GetPinRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPublicUserIcon implements getPublicUserIcon operation.
//
// ユーザーのアイコン画像を取得します。.
//
// GET /public/icon/{username}
func (UnimplementedHandler) GetPublicUserIcon(ctx context.Context, params GetPublicUserIconParams) (r GetPublicUserIconRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerVersion implements getServerVersion operation.
//
// サーバーバージョン及びサーバーフラグ情報を取得します。.
//
// GET /version
func (UnimplementedHandler) GetServerVersion(ctx context.Context) (r *Version, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStamp implements getStamp operation.
//
// 指定したスタンプの情報を取得します。.
//
// GET /stamps/{stampId}
func (UnimplementedHandler) GetStamp(ctx context.Context, params GetStampParams) (r GetStampRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStampImage implements getStampImage operation.
//
// 指定したIDのスタンプ画像を返します。.
//
// GET /stamps/{stampId}/image
func (UnimplementedHandler) GetStampImage(ctx context.Context, params GetStampImageParams) (r GetStampImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStampPalette implements getStampPalette operation.
//
// 指定したスタンプパレットの情報を取得します。.
//
// GET /stamp-palettes/{paletteId}
func (UnimplementedHandler) GetStampPalette(ctx context.Context, params GetStampPaletteParams) (r GetStampPaletteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStampPalettes implements getStampPalettes operation.
//
// 自身が所有しているスタンプパレットのリストを取得します。.
//
// GET /stamp-palettes
func (UnimplementedHandler) GetStampPalettes(ctx context.Context) (r []StampPalette, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStampStats implements getStampStats operation.
//
// 指定したスタンプの統計情報を取得します。.
//
// GET /stamps/{stampId}/stats
func (UnimplementedHandler) GetStampStats(ctx context.Context, params GetStampStatsParams) (r GetStampStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStamps implements getStamps operation.
//
// スタンプのリストを取得します。.
//
// GET /stamps
func (UnimplementedHandler) GetStamps(ctx context.Context, params GetStampsParams) (r []StampWithThumbnail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTag implements getTag operation.
//
// 指定したタグの情報を取得します。.
//
// GET /tags/{tagId}
func (UnimplementedHandler) GetTag(ctx context.Context, params GetTagParams) (r GetTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetThumbnailImage implements getThumbnailImage operation.
//
// 指定したファイルのサムネイル画像を取得します。
// 指定したファイルへのアクセス権限が必要です。.
//
// GET /files/{fileId}/thumbnail
func (UnimplementedHandler) GetThumbnailImage(ctx context.Context, params GetThumbnailImageParams) (r GetThumbnailImageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// 指定したユーザーの詳細情報を取得します。.
//
// GET /users/{userId}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserDMChannel implements getUserDMChannel operation.
//
// 指定したユーザーとのダイレクトメッセージチャンネルの情報を返します。
// ダイレクトメッセージチャンネルが存在しなかった場合、自動的に作成されます。.
//
// GET /users/{userId}/dm-channel
func (UnimplementedHandler) GetUserDMChannel(ctx context.Context, params GetUserDMChannelParams) (r GetUserDMChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserGroup implements getUserGroup operation.
//
// 指定したユーザーグループの情報を取得します。.
//
// GET /groups/{groupId}
func (UnimplementedHandler) GetUserGroup(ctx context.Context, params GetUserGroupParams) (r GetUserGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserGroupAdmins implements getUserGroupAdmins operation.
//
// 指定したグループの管理者のリストを取得します。.
//
// GET /groups/{groupId}/admins
func (UnimplementedHandler) GetUserGroupAdmins(ctx context.Context, params GetUserGroupAdminsParams) (r GetUserGroupAdminsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserGroupMembers implements getUserGroupMembers operation.
//
// 指定したグループのメンバーのリストを取得します。.
//
// GET /groups/{groupId}/members
func (UnimplementedHandler) GetUserGroupMembers(ctx context.Context, params GetUserGroupMembersParams) (r GetUserGroupMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserGroups implements getUserGroups operation.
//
// ユーザーグループのリストを取得します。.
//
// GET /groups
func (UnimplementedHandler) GetUserGroups(ctx context.Context) (r []UserGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserIcon implements getUserIcon operation.
//
// 指定したユーザーのアイコン画像を取得します。.
//
// GET /users/{userId}/icon
func (UnimplementedHandler) GetUserIcon(ctx context.Context, params GetUserIconParams) (r GetUserIconRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserSettings implements getUserSettings operation.
//
// ユーザー設定を取得します。.
//
// GET /users/me/settings
func (UnimplementedHandler) GetUserSettings(ctx context.Context) (r *UserSettings, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserStats implements getUserStats operation.
//
// 指定したユーザーの統計情報を取得します。.
//
// GET /users/{userId}/stats
func (UnimplementedHandler) GetUserStats(ctx context.Context, params GetUserStatsParams) (r GetUserStatsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserTags implements getUserTags operation.
//
// 指定したユーザーのタグリストを取得します。.
//
// GET /users/{userId}/tags
func (UnimplementedHandler) GetUserTags(ctx context.Context, params GetUserTagsParams) (r GetUserTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// ユーザーのリストを取得します。
// `include-suspended`を指定しない場合、レスポンスにはユーザーアカウント状態が"1: 有効"であるユーザーのみが含まれます。
// `include-suspended`と`name`を同時に指定することはできません。.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context, params GetUsersParams) (r GetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebRTCState implements getWebRTCState operation.
//
// 現在のWebRTC状態を取得します。.
//
// GET /webrtc/state
func (UnimplementedHandler) GetWebRTCState(ctx context.Context) (r WebRTCUserStates, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebhook implements getWebhook operation.
//
// 指定したWebhookの詳細を取得します。.
//
// GET /webhooks/{webhookId}
func (UnimplementedHandler) GetWebhook(ctx context.Context, params GetWebhookParams) (r GetWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebhookIcon implements getWebhookIcon operation.
//
// 指定したWebhookのアイコン画像を取得します.
//
// GET /webhooks/{webhookId}/icon
func (UnimplementedHandler) GetWebhookIcon(ctx context.Context, params GetWebhookIconParams) (r GetWebhookIconRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebhookMessages implements getWebhookMessages operation.
//
// 指定されたWebhookが投稿したメッセージのリストを返します。.
//
// GET /webhooks/{webhookId}/messages
func (UnimplementedHandler) GetWebhookMessages(ctx context.Context, params GetWebhookMessagesParams) (r GetWebhookMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebhooks implements getWebhooks operation.
//
// Webhookのリストを取得します。
// allがtrueで無い場合は、自分がオーナーのWebhookのリストを返します。.
//
// GET /webhooks
func (UnimplementedHandler) GetWebhooks(ctx context.Context, params GetWebhooksParams) (r []Webhook, _ error) {
	return r, ht.ErrNotImplemented
}

// InactivateBot implements inactivateBot operation.
//
// 指定したBOTを無効化します。対象のBOTの管理権限が必要です。.
//
// POST /bots/{botId}/actions/inactivate
func (UnimplementedHandler) InactivateBot(ctx context.Context, params InactivateBotParams) (r InactivateBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LetBotJoinChannel implements letBotJoinChannel operation.
//
// 指定したBOTを指定したチャンネルに参加させます。
// チャンネルに参加したBOTは、そのチャンネルの各種イベントを受け取るようになります。
// 対象のBOTの管理権限が必要です。.
//
// POST /bots/{botId}/actions/join
func (UnimplementedHandler) LetBotJoinChannel(ctx context.Context, req OptPostBotActionJoinRequest, params LetBotJoinChannelParams) (r LetBotJoinChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LetBotLeaveChannel implements letBotLeaveChannel operation.
//
// 指定したBOTを指定したチャンネルから退出させます。
// 対象のBOTの管理権限が必要です。.
//
// POST /bots/{botId}/actions/leave
func (UnimplementedHandler) LetBotLeaveChannel(ctx context.Context, req OptPostBotActionLeaveRequest, params LetBotLeaveChannelParams) (r LetBotLeaveChannelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LinkExternalAccount implements linkExternalAccount operation.
//
// 自分に外部ログインアカウントを紐付けます。
// 指定した`providerName`がサーバー側で有効である必要があります。
// リクエストが受理された場合、外部サービスの認証画面にリダイレクトされ、認証される必要があります。.
//
// POST /users/me/ex-accounts/link
func (UnimplementedHandler) LinkExternalAccount(ctx context.Context, req OptPostLinkExternalAccount) (r LinkExternalAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// ログインします。.
//
// POST /login
func (UnimplementedHandler) Login(ctx context.Context, req OptPostLoginRequest, params LoginParams) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// ログアウトします。.
//
// POST /logout
func (UnimplementedHandler) Logout(ctx context.Context, params LogoutParams) (r LogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostDirectMessage implements postDirectMessage operation.
//
// 指定したユーザーにダイレクトメッセージを送信します。.
//
// POST /users/{userId}/messages
func (UnimplementedHandler) PostDirectMessage(ctx context.Context, req OptPostMessageRequest, params PostDirectMessageParams) (r PostDirectMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostFile implements postFile operation.
//
// 指定したチャンネルにファイルをアップロードします。
// アーカイブされているチャンネルにはアップロード出来ません。.
//
// POST /files
func (UnimplementedHandler) PostFile(ctx context.Context, req OptPostFileRequestMultipart) (r PostFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostMessage implements postMessage operation.
//
// 指定したチャンネルにメッセージを投稿します。
// embedをtrueに指定すると、メッセージ埋め込みが自動で行われます。
// アーカイブされているチャンネルに投稿することはできません。.
//
// POST /channels/{channelId}/messages
func (UnimplementedHandler) PostMessage(ctx context.Context, req OptPostMessageRequest, params PostMessageParams) (r PostMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOAuth2Authorize implements postOAuth2Authorize operation.
//
// OAuth2 認可エンドポイント.
//
// POST /oauth2/authorize
func (UnimplementedHandler) PostOAuth2Authorize(ctx context.Context, req *OAuth2Authorization) (r PostOAuth2AuthorizeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOAuth2AuthorizeDecide implements postOAuth2AuthorizeDecide operation.
//
// OAuth2 認可承諾.
//
// POST /oauth2/authorize/decide
func (UnimplementedHandler) PostOAuth2AuthorizeDecide(ctx context.Context, req *OAuth2Decide) (r PostOAuth2AuthorizeDecideRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOAuth2Token implements postOAuth2Token operation.
//
// OAuth2 トークンエンドポイント.
//
// POST /oauth2/token
func (UnimplementedHandler) PostOAuth2Token(ctx context.Context, req *PostOAuth2Token) (r PostOAuth2TokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostWebRTCAuthenticate implements postWebRTCAuthenticate operation.
//
// Skyway WebRTC用の認証API.
//
// POST /webrtc/authenticate
func (UnimplementedHandler) PostWebRTCAuthenticate(ctx context.Context, req OptPostWebRTCAuthenticateRequest) (r PostWebRTCAuthenticateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostWebhook implements postWebhook operation.
//
// Webhookにメッセージを投稿します。
// secureなウェブフックに対しては`X-TRAQ-Signature`ヘッダーが必須です。
// アーカイブされているチャンネルには投稿できません。.
//
// POST /webhooks/{webhookId}
func (UnimplementedHandler) PostWebhook(ctx context.Context, req PostWebhookReq, params PostWebhookParams) (r PostWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadChannel implements readChannel operation.
//
// 自分が未読のチャンネルを既読にします。.
//
// DELETE /users/me/unread/{channelId}
func (UnimplementedHandler) ReadChannel(ctx context.Context, params ReadChannelParams) error {
	return ht.ErrNotImplemented
}

// RegisterFCMDevice implements registerFCMDevice operation.
//
// 自身のFCMデバイスを登録します。.
//
// POST /users/me/fcm-device
func (UnimplementedHandler) RegisterFCMDevice(ctx context.Context, req OptPostMyFCMDeviceRequest) (r RegisterFCMDeviceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReissueBot implements reissueBot operation.
//
// 指定したBOTの現在の各種トークンを無効化し、再発行を行います。
// 対象のBOTの管理権限が必要です。.
//
// POST /bots/{botId}/actions/reissue
func (UnimplementedHandler) ReissueBot(ctx context.Context, params ReissueBotParams) (r ReissueBotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveMessageStamp implements removeMessageStamp operation.
//
// 指定したメッセージから指定した自身が押したスタンプを削除します。.
//
// DELETE /messages/{messageId}/stamps/{stampId}
func (UnimplementedHandler) RemoveMessageStamp(ctx context.Context, params RemoveMessageStampParams) (r RemoveMessageStampRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveMyStar implements removeMyStar operation.
//
// 既にスターから削除されているチャンネルを指定した場合は204を返します。.
//
// DELETE /users/me/stars/{channelId}
func (UnimplementedHandler) RemoveMyStar(ctx context.Context, params RemoveMyStarParams) error {
	return ht.ErrNotImplemented
}

// RemoveMyUserTag implements removeMyUserTag operation.
//
// 既に存在しないタグを削除しようとした場合は204を返します。.
//
// DELETE /users/me/tags/{tagId}
func (UnimplementedHandler) RemoveMyUserTag(ctx context.Context, params RemoveMyUserTagParams) (r RemoveMyUserTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemovePin implements removePin operation.
//
// 指定したメッセージのピン留めを外します。.
//
// DELETE /messages/{messageId}/pin
func (UnimplementedHandler) RemovePin(ctx context.Context, params RemovePinParams) (r RemovePinRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveUserGroupAdmin implements removeUserGroupAdmin operation.
//
// 指定したユーザーグループから指定した管理者を削除します。
// 対象のユーザーグループの管理者権限が必要です。
// グループから管理者が存在しなくなる場合は400エラーを返します。.
//
// DELETE /groups/{groupId}/admins/{userId}
func (UnimplementedHandler) RemoveUserGroupAdmin(ctx context.Context, params RemoveUserGroupAdminParams) (r RemoveUserGroupAdminRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveUserGroupMember implements removeUserGroupMember operation.
//
// 指定したユーザーグループから指定したユーザーを削除します。
// 既にグループから削除されているメンバーを指定した場合は204を返します。
// 対象のユーザーグループの管理者権限が必要です。.
//
// DELETE /groups/{groupId}/members/{userId}
func (UnimplementedHandler) RemoveUserGroupMember(ctx context.Context, params RemoveUserGroupMemberParams) (r RemoveUserGroupMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveUserTag implements removeUserTag operation.
//
// 既に存在しないタグを削除しようとした場合は204を返します。.
//
// DELETE /users/{userId}/tags/{tagId}
func (UnimplementedHandler) RemoveUserTag(ctx context.Context, params RemoveUserTagParams) (r RemoveUserTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeClientTokens implements revokeClientTokens operation.
//
// 自分が許可している指定したOAuthクライアントのアクセストークンを全てRevokeします。.
//
// DELETE /clients/{clientId}/tokens
func (UnimplementedHandler) RevokeClientTokens(ctx context.Context, params RevokeClientTokensParams) (r RevokeClientTokensRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeMySession implements revokeMySession operation.
//
// 指定した自分のセッションを無効化(ログアウト)します。
// 既に存在しない・無効化されているセッションを指定した場合も`204`を返します。.
//
// DELETE /users/me/sessions/{sessionId}
func (UnimplementedHandler) RevokeMySession(ctx context.Context, params RevokeMySessionParams) error {
	return ht.ErrNotImplemented
}

// RevokeMyToken implements revokeMyToken operation.
//
// 自分の指定したトークンの認可を取り消します。.
//
// DELETE /users/me/tokens/{tokenId}
func (UnimplementedHandler) RevokeMyToken(ctx context.Context, params RevokeMyTokenParams) (r RevokeMyTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeOAuth2Token implements revokeOAuth2Token operation.
//
// OAuth2 トークン無効化エンドポイント.
//
// POST /oauth2/revoke
func (UnimplementedHandler) RevokeOAuth2Token(ctx context.Context, req *OAuth2Revoke) error {
	return ht.ErrNotImplemented
}

// SearchMessages implements searchMessages operation.
//
// メッセージを検索します。.
//
// GET /messages
func (UnimplementedHandler) SearchMessages(ctx context.Context, params SearchMessagesParams) (r SearchMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetChannelSubscribeLevel implements setChannelSubscribeLevel operation.
//
// 自身の指定したチャンネルの購読レベルを設定します。.
//
// PUT /users/me/subscriptions/{channelId}
func (UnimplementedHandler) SetChannelSubscribeLevel(ctx context.Context, req OptPutChannelSubscribeLevelRequest, params SetChannelSubscribeLevelParams) (r SetChannelSubscribeLevelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetChannelSubscribers implements setChannelSubscribers operation.
//
// 指定したチャンネルの通知購読者を設定します。
// リクエストに含めなかったユーザーの通知購読状態はオフになります。
// また、存在しないユーザーを指定した場合は無視されます。.
//
// PUT /channels/{channelId}/subscribers
func (UnimplementedHandler) SetChannelSubscribers(ctx context.Context, req OptPutChannelSubscribersRequest, params SetChannelSubscribersParams) (r SetChannelSubscribersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnclipMessage implements unclipMessage operation.
//
// 指定したフォルダから指定したメッセージのクリップを除外します。
// 既に外されているメッセージを指定した場合は204を返します。.
//
// DELETE /clip-folders/{folderId}/messages/{messageId}
func (UnimplementedHandler) UnclipMessage(ctx context.Context, params UnclipMessageParams) (r UnclipMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnlinkExternalAccount implements unlinkExternalAccount operation.
//
// 自分に紐付けられている外部ログインアカウントの紐付けを解除します。.
//
// POST /users/me/ex-accounts/unlink
func (UnimplementedHandler) UnlinkExternalAccount(ctx context.Context, req OptPostUnlinkExternalAccount) (r UnlinkExternalAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ws implements ws operation.
//
// # WebSocketプロトコル
// ## 送信
// `コマンド:引数1:引数2:...
// `のような形式のTextMessageをサーバーに送信することで、このWebSocketセッションに対する設定が実行できる。
// ### `viewstate`コマンド
// このWebSocketセッションが見ているチャンネル(イベントを受け取るチャンネル)を設定する。
// 現時点では1つのセッションに対して1つのチャンネルしか設定できない。
// `viewstate:{チャンネルID}:{閲覧状態}`
// + チャンネルID: 対象のチャンネルID
// + 閲覧状態: `none`, `monitoring`, `editing`
// 最初の`viewstate`コマンドを送る前、または`viewstate:null`,
// `viewstate:`を送信した後は、このセッションはどこのチャンネルも見ていないことになる。
// ### `rtcstate`コマンド
// 自分のWebRTC状態を変更する。
// 他のコネクションが既に状態を保持している場合、変更することができません。
// `rtcstate:{チャンネルID}:({状態}:{セッションID})*`
// コネクションが切断された場合、自分のWebRTC状態はリセットされます。
// ### `timeline_streaming`コマンド
// 全てのパブリックチャンネルの`MESSAGE_CREATED`イベントを受け取るかどうかを設定する。
// 初期状態は`off`です。
// `timeline_streaming:(on|off|true|false)`
// ## 受信
// TextMessageとして各種イベントが`type`と`body`を持つJSONとして非同期に送られます。
// 例:
// ```json
// {"type":"USER_ONLINE","body":{"id":"7dd8e07f-7f5d-4331-9176-b56a4299768b"}}
// ```
// ## イベント一覧
// ### `USER_JOINED`
// ユーザーが新規登録された。
// 対象: 全員
// + `id`: 登録されたユーザーのId
// ### `USER_UPDATED`
// ユーザーの情報が更新された。
// 対象: 全員
// + `id`: 情報が更新されたユーザーのId
// ### `USER_TAGS_UPDATED`
// ユーザーのタグが更新された。
// 対象: 全員
// + `id`: タグが更新されたユーザーのId
// + `tag_id`: 更新されたタグのId
// ### `USER_ICON_UPDATED`
// ユーザーのアイコンが更新された。
// 対象: 全員
// + `id`: アイコンが更新されたユーザーのId
// ### `USER_WEBRTC_STATE_CHANGED`
// ユーザーのWebRTCの状態が変化した
// 対象: 全員
// + `user_id`: 変更があったユーザーのId
// + `channel_id`: ユーザーの変更後の接続チャンネルのId
// + `sessions`: ユーザーの変更後の状態(配列)
// + `state`: 状態
// + `sessionId`: セッションID
// ### `USER_VIEWSTATE_CHANGED`
// ユーザーのチャンネルの閲覧状態が変化した
// 対象: 変化したWSセッションを含めた、該当ユーザーのWSセッション全て
// + `view_states`:
// 変化したWSセッションを含めた、該当ユーザーの変更後の状態(配列)
// + `key`: WSセッションの識別子
// + `channel_id`: 閲覧しているチャンネルId
// + `state`: 閲覧状態
// ### `USER_ONLINE`
// ユーザーがオンラインになった。
// 対象: 全員
// + `id`: オンラインになったユーザーのId
// ### `USER_OFFLINE`
// ユーザーがオフラインになった。
// 対象: 全員
// + `id`: オフラインになったユーザーのId
// ### `USER_GROUP_CREATED`
// ユーザーグループが作成された
// 対象: 全員
// + `id`: 作成されたユーザーグループのId
// ### `USER_GROUP_UPDATED`
// ユーザーグループが更新された
// 対象: 全員
// + `id`: 作成されたユーザーグループのId
// ### `USER_GROUP_DELETED`
// ユーザーグループが削除された
// 対象: 全員
// + `id`: 削除されたユーザーグループのId
// ### `CHANNEL_CREATED`
// チャンネルが新規作成された。
// 対象: 該当チャンネルを閲覧可能な全員
// + `id`: 作成されたチャンネルのId
// + `dm_user_id`: (DMの場合のみ) DM相手のユーザーId
// ### `CHANNEL_UPDATED`
// チャンネルの情報が変更された。
// 対象: 該当チャンネルを閲覧可能な全員
// + `id`: 変更があったチャンネルのId
// + `dm_user_id`: (DMの場合のみ) DM相手のユーザーId
// ### `CHANNEL_DELETED`
// チャンネルが削除された。
// 対象: 該当チャンネルを閲覧可能な全員
// + `id`: 削除されたチャンネルのId
// + `dm_user_id`: (DMの場合のみ) DM相手のユーザーId
// ### `CHANNEL_STARED`
// 自分がチャンネルをスターした。
// 対象: 自分
// + `id`: スターしたチャンネルのId
// ### `CHANNEL_UNSTARED`
// 自分がチャンネルのスターを解除した。
// 対象: 自分
// + `id`: スターしたチャンネルのId
// ### `CHANNEL_VIEWERS_CHANGED`
// チャンネルの閲覧者が変化した。
// 対象: 該当チャンネルを閲覧しているユーザー
// + `id`: 変化したチャンネルのId
// + `viewers`: 変化後の閲覧者(配列)
// + `userId`: ユーザーId
// + `state`: 閲覧状態
// + `updatedAt`: 閲覧状態の更新日時
// ### `CHANNEL_SUBSCRIBERS_CHANGED`
// チャンネルの購読者が変化した。
// 対象: 該当チャンネルを閲覧しているユーザー
// + `id`: 変化したチャンネルのId
// ### `MESSAGE_CREATED`
// メッセージが投稿された。
// 対象:
// 投稿チャンネルを閲覧しているユーザー・投稿チャンネルに通知をつけているユーザー・メンションを受けたユーザー
// + `id`: 投稿されたメッセージのId
// + `is_citing`:
// 投稿されたメッセージがWebSocketを接続しているユーザーの投稿を引用しているかどうか
// ### `MESSAGE_UPDATED`
// メッセージが更新された。
// 対象: 投稿チャンネルを閲覧しているユーザー
// + `id`: 更新されたメッセージのId
// ### `MESSAGE_DELETED`
// メッセージが削除された。
// 対象: 投稿チャンネルを閲覧しているユーザー
// + `id`: 削除されたメッセージのId
// ### `MESSAGE_STAMPED`
// メッセージにスタンプが押された。
// 対象: 投稿チャンネルを閲覧しているユーザー
// + `message_id`: メッセージId
// + `user_id`: スタンプを押したユーザーのId
// + `stamp_id`: スタンプのId
// + `count`: そのユーザーが押した数
// + `created_at`:
// そのユーザーがそのスタンプをそのメッセージに最初に押した日時
// ### `MESSAGE_UNSTAMPED`
// メッセージからスタンプが外された。
// 対象: 投稿チャンネルを閲覧しているユーザー
// + `message_id`: メッセージId
// + `user_id`: スタンプを押したユーザーのId
// + `stamp_id`: スタンプのId
// ### `MESSAGE_PINNED`
// メッセージがピン留めされた。
// 対象: 投稿チャンネルを閲覧しているユーザー
// + `message_id`: ピンされたメッセージのID
// + `channel_id`: ピンされたメッセージのチャンネルID
// ### `MESSAGE_UNPINNED`
// ピン留めされたメッセージのピンが外された。
// 対象: 投稿チャンネルを閲覧しているユーザー
// + `message_id`: ピンが外されたメッセージのID
// + `channel_id`: ピンが外されたメッセージのチャンネルID
// ### `MESSAGE_READ`
// 自分があるチャンネルのメッセージを読んだ。
// 対象: 自分
// + `id`: 読んだチャンネルId
// ### `STAMP_CREATED`
// スタンプが新しく追加された。
// 対象: 全員
// + `id`: 作成されたスタンプのId
// ### `STAMP_UPDATED`
// スタンプが修正された。
// 対象: 全員
// + `id`: 修正されたスタンプのId
// ### `STAMP_DELETED`
// スタンプが削除された。
// 対象: 全員
// + `id`: 削除されたスタンプのId
// ### `STAMP_PALETTE_CREATED`
// スタンプパレットが新しく追加された。
// 対象: 自分
// + `id`: 作成されたスタンプパレットのId
// ### `STAMP_PALETTE_UPDATED`
// スタンプパレットが修正された。
// 対象: 自分
// + `id`: 修正されたスタンプパレットのId
// ### `STAMP_PALETTE_DELETED`
// スタンプパレットが削除された。
// 対象: 自分
// + `id`: 削除されたスタンプパレットのId
// ### `CLIP_FOLDER_CREATED`
// クリップフォルダーが作成された。
// 対象：自分
// + `id`: 作成されたクリップフォルダーのId
// ### `CLIP_FOLDER_UPDATED`
// クリップフォルダーが修正された。
// 対象: 自分
// + `id`: 更新されたクリップフォルダーのId
// ### `CLIP_FOLDER_DELETED`
// クリップフォルダーが削除された。
// 対象: 自分
// + `id`: 削除されたクリップフォルダーのId
// ### `CLIP_FOLDER_MESSAGE_DELETED`
// クリップフォルダーからメッセージが除外された。
// 対象: 自分
// + `folder_id`: メッセージが除外されたクリップフォルダーのId
// + `message_id`: クリップフォルダーから除外されたメッセージのId
// ### `CLIP_FOLDER_MESSAGE_ADDED`
// クリップフォルダーにメッセージが追加された。
// 対象: 自分
// + `folder_id`: メッセージが追加されたクリップフォルダーのId
// + `message_id`: クリップフォルダーに追加されたメッセージのId.
//
// GET /ws
func (UnimplementedHandler) Ws(ctx context.Context) error {
	return ht.ErrNotImplemented
}
